[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."gmail-watch-renew"]
  schedule = "@daily"

[dev]
  functions = "netlify/functions"
  publish = "."
