(function(){
  if(window.__ROUTEX_HOUSECIRCLE_V69__) return;
  window.__ROUTEX_HOUSECIRCLE_V69__ = true;
  var KEY = 'skye_routex_platform_house_circle_neon_v69';
  var VAL_KEY_OLD = 'skye_routex_platform_house_circle_valuation_v68';
  var VAL_KEY_NEW = 'skye_routex_platform_house_circle_valuation_v69';
  var clean = window.cleanStr || function(v){ return String(v == null ? '' : v).trim(); };
  var esc = window.escapeHTML || function(v){ return String(v == null ? '' : v); };
  var nowFn = typeof nowISO === 'function' ? nowISO : function(){ return new Date().toISOString(); };
  var toastFn = typeof toast === 'function' ? toast : function(){};
  var openModalFn = typeof openModal === 'function' ? openModal : function(title){ try{ alert(title); }catch(_){} };
  var raf = typeof requestAnimationFrame === 'function' ? requestAnimationFrame.bind(window) : function(cb){ return setTimeout(cb, 0); };
  function num(v){ var n = Number(v || 0); return Number.isFinite(n) ? n : 0; }
  function readJSON(key, fallback){ try{ var raw = localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; }catch(_){ return fallback; } }
  function writeJSON(key, value){ localStorage.setItem(key, JSON.stringify(value)); return value; }
  function valuationRecord(){ return { type:'skye-routexflow-codebase-valuation-v69', version:'69.0.0', title:'SkyeRoutexFlow + Platform House Circle — 2026 Codebase Valuation', asOf:'2026-04-04 America/Phoenix', currency:'USD', totalValue:5950000, generatedAt:nowFn(), status:'Current codebase enterprise valuation', valuationMethod:'Enterprise replacement-cost-plus productization premium', summary:'This valuation reflects the full current codebase including the new enterprise-grade Neon backup lane.', discoverability:{ html:'./investor/SKYEROUTEXFLOW_V69_2026_ENTERPRISE_VALUATION.html', markdown:'./investor/SKYEROUTEXFLOW_V69_2026_ENTERPRISE_VALUATION.md', json:'./investor/SKYEROUTEXFLOW_V69_2026_ENTERPRISE_VALUATION.json' } }; }
  function syncValuationKeys(){ var record = valuationRecord(); writeJSON(VAL_KEY_OLD, record); writeJSON(VAL_KEY_NEW, record); return record; }
  function readCloudConfig(){ try{ if(window.RoutexPlatformHouseCircleV64 && typeof window.RoutexPlatformHouseCircleV64.readCloudConfig === 'function') return window.RoutexPlatformHouseCircleV64.readCloudConfig(); }catch(_){} return { enabled:false, baseUrl:'' }; }
  function readCloudSession(){ try{ if(window.RoutexPlatformHouseCircleV64 && typeof window.RoutexPlatformHouseCircleV64.readCloudSession === 'function') return window.RoutexPlatformHouseCircleV64.readCloudSession(); }catch(_){} return null; }
  function apiUrl(path){ var cfg = readCloudConfig() || {}; var base = clean(cfg.baseUrl || ''); if(!base) return null; return base.replace(/\/$/, '') + path; }
  async function call(path, init){ var url = apiUrl(path); if(!url) throw new Error('Cloud base URL not configured.'); var session = readCloudSession() || {}; init = init || {}; init.headers = Object.assign({ 'content-type':'application/json' }, init.headers || {}, session.token ? { authorization:'Bearer ' + session.token } : {}); var res = await fetch(url, init); var data = await res.json().catch(function(){ return {}; }); if(!res.ok || data.ok === false) throw new Error(clean(data.error || data.reason || ('Request failed (' + res.status + ')'))); return data; }
  async function neonHealth(){ try{ var data = await call('/phc-neon-health?orgId=default-org', { method:'GET' }); writeJSON(KEY, { at: nowFn(), data: data }); return data; }catch(err){ var fallback = { ok:false, neon:{ configured:false, reason: clean(err && err.message) || 'Neon lane unavailable.' } }; writeJSON(KEY, { at: nowFn(), data: fallback }); return fallback; } }
  async function pushBackup(){ return call('/phc-neon-backup-push', { method:'POST', body: JSON.stringify({ orgId:'default-org', reason:'UI-triggered V69 Neon backup push' }) }); }
  async function pullBackup(mode){ return call('/phc-neon-backup-pull', { method:'POST', body: JSON.stringify({ orgId:'default-org', mode: mode || 'merge' }) }); }
  function openNeonModal(){ var cached = readJSON(KEY, null); var neon = cached && cached.data && cached.data.neon || {}; openModalFn('Neon enterprise backup lane · V69', '<div class="hint">The primary shipped persistence lane remains file-backed so nothing breaks. V69 adds Neon as an additional enterprise-grade backup/restore lane wired into the live stack.</div><div class="sep"></div><div class="row" style="flex-wrap:wrap;gap:10px;"><div class="pill">Mode file + neon backup</div><div class="pill">Configured ' + esc(neon.configured ? 'yes' : 'no') + '</div><div class="pill">Latest snapshot ' + esc(neon.latestSnapshot && neon.latestSnapshot.generated_at ? neon.latestSnapshot.generated_at : 'none yet') + '</div></div><div class="sep"></div><div class="hint"><strong>What this lane does:</strong><br/>Push the current server state into Neon as a durable SQL snapshot, pull the latest snapshot back into the platform, and surface enterprise backup health from the live UI.</div><div class="sep"></div><div class="hint">Static schema path: ./neon/PHC_NEON_SCHEMA_V69.sql<br/>Deploy guide: ./neon/PHC_NEON_DEPLOY_GUIDE_V69.md</div>', '<button class="btn" id="hc69_neon_health">Refresh health</button><button class="btn" id="hc69_neon_push">Push backup</button><button class="btn" id="hc69_neon_pull">Pull backup</button><button class="btn" id="hc69_neon_schema">Open schema</button><button class="btn primary" id="hc69_neon_guide">Open guide</button>'); function bind(id, fn){ var el = document.getElementById(id); if(el) el.onclick = fn; } bind('hc69_neon_health', async function(){ try{ await neonHealth(); openNeonModal(); toastFn('Neon health refreshed.', 'ok'); }catch(err){ toastFn(clean(err && err.message) || 'Neon health failed.', 'bad'); } }); bind('hc69_neon_push', async function(){ try{ await pushBackup(); await neonHealth(); openNeonModal(); toastFn('Neon backup pushed.', 'ok'); }catch(err){ toastFn(clean(err && err.message) || 'Neon backup push failed.', 'bad'); } }); bind('hc69_neon_pull', async function(){ try{ await pullBackup('merge'); await neonHealth(); if(typeof render === 'function') render(); openNeonModal(); toastFn('Neon backup pulled and merged.', 'ok'); }catch(err){ toastFn(clean(err && err.message) || 'Neon backup pull failed.', 'bad'); } }); bind('hc69_neon_schema', function(){ try{ window.open('./neon/PHC_NEON_SCHEMA_V69.sql', '_blank'); }catch(_){} }); bind('hc69_neon_guide', function(){ try{ window.open('./neon/PHC_NEON_DEPLOY_GUIDE_V69.md', '_blank'); }catch(_){} }); }
  function injectStyles(){ if(document.getElementById('hc_v69_styles')) return; var style = document.createElement('style'); style.id = 'hc_v69_styles'; style.textContent = '.hc-v69-kpi{min-width:160px;padding:14px 16px;border:1px solid rgba(255,255,255,.12);border-radius:16px;background:rgba(111,233,255,.07)}.hc-v69-kpi .n{font-size:1.2rem;font-weight:800;color:#6fe9ff}.hc-v69-kpi .d{font-size:.82rem;opacity:.82}'; (document.head || document.body).appendChild(style); }
  function renderNeonCard(){ if(!(typeof APP !== 'undefined' && APP && (APP.view === 'platform-house' || APP.view === 'dashboard' || APP.view === 'settings'))) return; var host = document.querySelector('#content') || document.querySelector('#app') || document.body; if(!host) return; var old = document.getElementById('hc_v69_card'); if(old && old.remove) old.remove(); var cached = readJSON(KEY, null); var neon = cached && cached.data && cached.data.neon || {}; var card = document.createElement('div'); card.id = 'hc_v69_card'; card.className = 'card hc-v69-card'; card.innerHTML = '<h2 style="margin:0 0 8px;">Neon enterprise backup lane · V69</h2><div class="hint">The shipped file-backed persistence lane remains intact. Neon is now wired in as an additional enterprise-grade backup, restore, and durability lane.</div><div class="sep"></div><div class="row" style="flex-wrap:wrap;gap:12px;"><div class="hc-v69-kpi"><div class="n">' + esc(neon.configured ? 'ready' : 'not configured') + '</div><div class="d">Neon status</div></div><div class="hc-v69-kpi"><div class="n">' + esc(neon.latestSnapshot && neon.latestSnapshot.revision ? neon.latestSnapshot.revision : 'none yet') + '</div><div class="d">Latest snapshot</div></div><div class="hc-v69-kpi"><div class="n">file + neon</div><div class="d">Dual-lane posture</div></div></div><div class="sep"></div><div class="row" style="justify-content:flex-end;flex-wrap:wrap;"><button class="btn" id="hc69_card_health">Refresh health</button><button class="btn" id="hc69_card_push">Push backup</button><button class="btn" id="hc69_card_pull">Pull backup</button><button class="btn primary" id="hc69_card_open">Open Neon lane</button></div>'; host.appendChild(card); var bind = function(id, fn){ var el = document.getElementById(id); if(el) el.onclick = fn; }; bind('hc69_card_open', openNeonModal); bind('hc69_card_health', async function(){ await neonHealth(); if(typeof render === 'function') render(); }); bind('hc69_card_push', async function(){ try{ await pushBackup(); await neonHealth(); if(typeof render === 'function') render(); toastFn('Neon backup pushed.', 'ok'); }catch(err){ toastFn(clean(err && err.message) || 'Neon backup push failed.', 'bad'); } }); bind('hc69_card_pull', async function(){ try{ await pullBackup('merge'); await neonHealth(); if(typeof render === 'function') render(); toastFn('Neon backup pulled.', 'ok'); }catch(err){ toastFn(clean(err && err.message) || 'Neon backup pull failed.', 'bad'); } }); }
  function injectToolbarButton(){ if(document.getElementById('hc69_toolbar_btn')) return; var hosts = []; if(typeof document.querySelectorAll === 'function'){ try{ hosts = Array.prototype.slice.call(document.querySelectorAll('.topbar .row, #nav')); }catch(_){ hosts = []; } } for(var i=0;i<hosts.length;i++){ var host = hosts[i]; if(!host) continue; var btn = document.createElement('button'); btn.id = 'hc69_toolbar_btn'; btn.className = host.id === 'nav' ? 'navbtn' : 'btn'; btn.innerHTML = host.id === 'nav' ? '<span>🗄️</span><div class="l"><b>Neon</b><span>Backup lane</span></div>' : 'Neon'; btn.onclick = function(){ openNeonModal(); }; host.appendChild(btn); break; } }
  function patchRender(){ if(window.__HC_V69_RENDER_PATCHED__) return; window.__HC_V69_RENDER_PATCHED__ = true; var prev = typeof render === 'function' ? render : null; if(prev){ render = async function(){ var out = await prev.apply(this, arguments); try{ injectStyles(); injectToolbarButton(); renderNeonCard(); }catch(_){} return out; }; } }
  function bootstrap(){ syncValuationKeys(); injectStyles(); injectToolbarButton(); patchRender(); neonHealth().catch(function(){}); try{ var cfg = readCloudConfig(); var session = readCloudSession(); if(cfg && cfg.enabled && session && session.token){ setTimeout(function(){ pushBackup().catch(function(){}); }, 1400); } }catch(_){} raf(function(){ try{ if(typeof render === 'function') render(); else renderNeonCard(); }catch(_){} }); }
  bootstrap();
  window.RoutexPlatformHouseCircleV69 = { valuationRecord: valuationRecord, neonHealth: neonHealth, pushBackup: pushBackup, pullBackup: pullBackup, openNeonModal: openNeonModal, syncValuationKeys: syncValuationKeys };
})();
