const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const ROOT = __dirname;
const DATA_DIR = path.join(ROOT, '.phc_data_v83_smoke');
const FABRIC_DIR = path.join(ROOT, 'netlify', '.phc_app_fabric_v83_smoke');
fs.rmSync(DATA_DIR, { recursive:true, force:true });
fs.rmSync(FABRIC_DIR, { recursive:true, force:true });
process.env.PHC_DATA_DIR = DATA_DIR;
process.env.PHC_APP_FABRIC_DIR = FABRIC_DIR;
process.env.PHC_SESSION_SECRET = 'v83-session-secret-abcdefghijklmnopqrstuvwxyz-123456789';
process.env.PHC_OPERATOR_PASSWORD = 'v83-password';
process.env.PHC_OPERATOR_ROLE = 'admin';
process.env.PHC_ALLOW_PROVIDER_NETWORK = '';
process.env.PHC_NEON_AUTOMIRROR = '';
process.env.PHC_REQUIRE_NEON_PRIMARY = '';
process.env.PHC_ALLOW_UNSIGNED_WEBHOOKS = '';
process.env.PHC_PRODUCTION = '';
process.env.PHC_ALLOW_BOOTSTRAP_LOGIN = '';

const login = require('./netlify/functions/phc-auth-login').handler;
const health = require('./netlify/functions/phc-health').handler;
const syncState = require('./netlify/functions/phc-sync-state').handler;
const paymentHealth = require('./netlify/functions/phc-payment-provider-health').handler;
const paymentIntent = require('./netlify/functions/phc-payment-intent').handler;
const refundIntent = require('./netlify/functions/phc-refund-intent').handler;
const stripeWebhook = require('./netlify/functions/phc-webhook-stripe').handler;
const paypalWebhook = require('./netlify/functions/phc-webhook-paypal').handler;
const persistencePolicyRoute = require('./netlify/functions/phc-persistence-policy').handler;
const deadButtonAudit = require('./netlify/functions/phc-app-fabric-dead-button-audit').handler;
const deploymentReceipts = require('./netlify/functions/phc-app-fabric-deployment-receipts').handler;
const zeroSMount = require('./netlify/functions/phc-app-fabric-0s-mount').handler;
const { readOrgState } = require('./netlify/functions/_lib/housecircle-cloud-store');
const { persistencePolicy, persistOrgState } = require('./netlify/functions/_lib/housecircle-persistence');
const { productionReadiness } = require('./netlify/functions/_lib/housecircle-runtime-guard');
const { PHC_SCHEMA_SQL, readNeonConfig } = require('./netlify/functions/_lib/housecircle-neon-store');

function event(method, body, token, query, headers){ const h={ 'content-type':'application/json', ...(headers||{}) }; if(token) h.authorization='Bearer '+token; return { httpMethod:method, headers:h, queryStringParameters:query||{}, body: body===undefined ? '' : (typeof body === 'string' ? body : JSON.stringify(body)) }; }
function parsed(res){ try{ return JSON.parse(res.body || '{}'); }catch(_){ return {}; } }
const results=[];
async function check(name, fn){ try{ const detail=await fn(); const ok=detail===true || !!(detail && detail.ok); results.push({ name, ok, detail:detail===true?{}:detail }); }catch(err){ results.push({ name, ok:false, error:err && err.stack || String(err) }); } }
async function doLogin(){ const res=await login(event('POST',{ orgId:'v83-org', operatorId:'founder-admin', operatorName:'Skyes Over London', role:'admin', password:'v83-password', deviceId:'device-admin' })); return { res, body:parsed(res) }; }
(async()=>{
  const admin = await doLogin(); const token=admin.body.token;
  await check('V83 login creates active revocation-aware session', async()=>{ const state=readOrgState('v83-org'); return { ok:admin.res.statusCode===200 && !!token && state.sessions.length===1 && state.sessions[0].trustedDevice===true, statusCode:admin.res.statusCode, sessions:state.sessions.length }; });
  await check('V83 health is auth locked', async()=>{ const denied=await health({ httpMethod:'GET', headers:{}, queryStringParameters:{ orgId:'v83-org' }, body:'' }); const allowed=await health({ httpMethod:'GET', headers:{ authorization:'Bearer '+token }, queryStringParameters:{ orgId:'v83-org' }, body:'' }); return { ok:denied.statusCode===401 && allowed.statusCode===200 && parsed(allowed).storage.productionRequirement.includes('not deployed DNS/SSL proof'), denied:denied.statusCode, allowed:allowed.statusCode }; });
  await check('V83 strict Neon-primary blocks before local JSON write when Neon env is absent', async()=>{ const before = fs.existsSync(path.join(DATA_DIR,'strict-neon-org.json')); process.env.PHC_REQUIRE_NEON_PRIMARY='1'; delete process.env.NEON_DATABASE_URL; delete process.env.DATABASE_URL; let blocked=false, message=''; try{ await persistOrgState('strict-neon-org', { orgId:'strict-neon-org', bundle:{}, sessions:[] }, { eventKind:'strict_test' }); }catch(err){ blocked=true; message=String(err.message||''); } process.env.PHC_REQUIRE_NEON_PRIMARY=''; const after = fs.existsSync(path.join(DATA_DIR,'strict-neon-org.json')); return { ok:blocked && !before && !after && /Local fallback write was blocked/.test(message), blocked, before, after, message }; });
  await check('V83 persistence policy route is locked and labels local mode honestly', async()=>{ const denied=await persistencePolicyRoute({ httpMethod:'GET', headers:{}, queryStringParameters:{ orgId:'v83-org' }, body:'' }); const allowed=await persistencePolicyRoute({ httpMethod:'GET', headers:{ authorization:'Bearer '+token }, queryStringParameters:{ orgId:'v83-org' }, body:'' }); const body=parsed(allowed); return { ok:denied.statusCode===401 && allowed.statusCode===200 && body.policy && body.policy.mode==='file-primary-local', denied:denied.statusCode, policy:body.policy }; });
  await check('V83 sync-state writes through persistence wrapper', async()=>{ const res=await syncState(event('POST',{ orgId:'v83-org', bundle:{ state:{ locations:[{ id:'v83-loc', name:'V83 Location', updatedAt:new Date().toISOString() }] } }, reason:'v83 smoke sync' }, token)); const state=readOrgState('v83-org'); return { ok:res.statusCode===200 && state.eventLog.some((row)=>row.kind==='persistence_policy'), statusCode:res.statusCode, eventCount:state.eventLog.length }; });
  await check('V83 production readiness refuses plaintext/bootstrap-only credentials', async()=>{ const oldProd=process.env.PHC_PRODUCTION, oldPlain=process.env.PHC_OPERATOR_PASSWORD, oldHash=process.env.PHC_OPERATOR_PASSWORD_HASH, oldSalt=process.env.PHC_OPERATOR_PASSWORD_SALT; process.env.PHC_PRODUCTION='1'; process.env.PHC_OPERATOR_PASSWORD='plain-prod-password'; delete process.env.PHC_OPERATOR_PASSWORD_HASH; delete process.env.PHC_OPERATOR_PASSWORD_SALT; const ready=productionReadiness(); process.env.PHC_PRODUCTION=oldProd||''; process.env.PHC_OPERATOR_PASSWORD=oldPlain||''; if(oldHash) process.env.PHC_OPERATOR_PASSWORD_HASH=oldHash; else delete process.env.PHC_OPERATOR_PASSWORD_HASH; if(oldSalt) process.env.PHC_OPERATOR_PASSWORD_SALT=oldSalt; else delete process.env.PHC_OPERATOR_PASSWORD_SALT; return { ok:ready.ok===false && ready.failing.some((row)=>row.key==='operatorCredentialHashInProduction'), failing:ready.failing }; });
  await check('V83 Neon schema contains operational tables, not snapshot-only mirror', async()=>{ const required=['phc_operational_events','phc_payment_ledger','phc_webhook_replay_ledger','phc_active_sessions']; return { ok:required.every((name)=>PHC_SCHEMA_SQL.includes(name)), required, mode:readNeonConfig().mode }; });
  await check('V83 provider health reports no live execution without env/network', async()=>{ const res=await paymentHealth({ httpMethod:'GET', headers:{ authorization:'Bearer '+token }, queryStringParameters:{ orgId:'v83-org' }, body:'' }); const body=parsed(res); return { ok:res.statusCode===200 && body.providers.every((p)=>p.liveExecutionReady===false), providers:body.providers.map((p)=>({provider:p.provider, ready:p.liveExecutionReady})) }; });
  await check('V83 payment/refund ledgers do not claim money movement when network is blocked', async()=>{ process.env.STRIPE_SECRET_KEY='sk_test_v83_fake'; process.env.PHC_ALLOW_PROVIDER_NETWORK=''; const pay=await paymentIntent(event('POST',{ orgId:'v83-org', provider:'stripe', amountCents:2200, currency:'USD', orderId:'order-v83-network-blocked' }, token)); const ref=await refundIntent(event('POST',{ orgId:'v83-org', provider:'stripe', amountCents:1100, currency:'USD', paymentIntentId:'pi_fake_v83', idempotencyKey:'refund-v83' }, token)); const b1=parsed(pay), b2=parsed(ref); const state=readOrgState('v83-org'); return { ok:pay.statusCode===503 && ref.statusCode===503 && b1.liveMoneyMoved===false && b2.liveMoneyMoved===false && state.paymentLedger.length>=2, paymentStatus:b1.ledger&&b1.ledger.status, refundStatus:b2.ledger&&b2.ledger.status, ledger:state.paymentLedger.length }; });
  await check('V83 signed Stripe webhook persists through persistence wrapper and denies replay', async()=>{ process.env.STRIPE_WEBHOOK_SECRET='whsec_v83'; const payload=JSON.stringify({ id:'evt_v83_stripe_1', type:'payment_intent.succeeded', orgId:'v83-org', data:{ object:{ metadata:{ orgId:'v83-org' } } } }); const t=Math.floor(Date.now()/1000).toString(); const sig=crypto.createHmac('sha256', process.env.STRIPE_WEBHOOK_SECRET).update(t+'.'+payload).digest('hex'); const first=await stripeWebhook(event('POST', payload, '', {}, { 'Stripe-Signature':'t='+t+',v1='+sig })); const second=await stripeWebhook(event('POST', payload, '', {}, { 'Stripe-Signature':'t='+t+',v1='+sig })); const state=readOrgState('v83-org'); return { ok:first.statusCode===200 && second.statusCode===409 && state.eventLog.some((row)=>row.kind==='persistence_policy'), first:parsed(first), second:parsed(second) }; });
  await check('V83 PayPal verification path refuses fake success without network and has real verify call available', async()=>{ process.env.PAYPAL_WEBHOOK_ID='paypal-webhook-v83'; process.env.PHC_ALLOW_PROVIDER_NETWORK=''; process.env.PAYPAL_CLIENT_ID='client'; process.env.PAYPAL_CLIENT_SECRET='secret'; const headers={ 'paypal-transmission-id':'tx-v83', 'paypal-transmission-time':new Date().toISOString(), 'paypal-cert-url':'https://api.paypal.com/cert.pem', 'paypal-auth-algo':'SHA256withRSA', 'paypal-transmission-sig':'sig' }; const res=await paypalWebhook(event('POST',{ id:'WH-v83-2', event_type:'PAYMENT.CAPTURE.COMPLETED', orgId:'v83-org' }, '', {}, headers)); const providerFile=fs.readFileSync(path.join(ROOT,'netlify/functions/_lib/housecircle-payment-providers.js'),'utf8'); return { ok:res.statusCode===503 && parsed(res).verificationReady===true && providerFile.includes('/v1/notifications/verify-webhook-signature') && providerFile.includes('/v1/oauth2/token'), statusCode:res.statusCode, body:parsed(res) }; });
  await check('V83 App Fabric static audit says it is not browser click automation', async()=>{ const res=await deadButtonAudit(event('POST',{ orgId:'v83-org' }, token)); const body=parsed(res); return { ok:res.statusCode===200 && body.audit && body.audit.browserClickProof===false && body.audit.proofScope==='static-file-analysis-not-browser-click-automation', scope:body.audit && body.audit.proofScope }; });
  await check('V83 deployment receipts are local-readiness only', async()=>{ const res=await deploymentReceipts(event('POST',{ orgId:'v83-org' }, token)); const body=parsed(res); const receipts=body.receipts||[]; return { ok:res.statusCode===200 && receipts.length>0 && receipts.every((r)=>r.deploymentProof===false && r.liveProviderProof===false && /local readiness only/i.test(r.note||'')), statuses:receipts.map((r)=>r.status).slice(0,5) }; });
  await check('V83 0s mount does not claim sandbox/process runtime', async()=>{ const res=await zeroSMount(event('POST',{ orgId:'v83-org' }, token)); const body=parsed(res); return { ok:res.statusCode===200 && body.mountPlan && body.mountPlan.mountMode==='shell-manifest-mount-not-process-or-sandbox-runtime', mode:body.mountPlan && body.mountPlan.mountMode }; });

  await check('V83 index runtime wiring exists', async()=>{ const html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'); return { ok:html.includes('const platform =') && html.includes('data-action=') && html.includes('async function pingRuntime') && html.includes('./v1/runtime-summary'), inlineRuntime:true }; });

  await check('V83 package is pruned of old smoke/state/directive residue', async()=>{ const forbidden=[]; function walk(dir){ for(const item of fs.readdirSync(dir,{withFileTypes:true})){ const p=path.join(dir,item.name); const rel=path.relative(ROOT,p).replace(/\\/g,'/'); if(item.isDirectory()){ if(/^WHITE_GLOVE_V8[12]$/.test(item.name) || /^\.phc_data_v8[12]/.test(item.name) || /\.phc_app_fabric_v77/.test(rel)) forbidden.push(rel); else walk(p); } else { if(/PLATFORM_HOUSE_CIRCLE_SMOKE_V8[12]\.js$/.test(item.name) || /MASSIVE_HARDENING_DIRECTIVE_V8[12]\.md$/.test(item.name) || /V8[12]_IMPLEMENTATION_STATUS\.md$/.test(item.name)) forbidden.push(rel); } } } walk(ROOT); return { ok:forbidden.length===0, forbidden }; });

  const passed=results.filter((r)=>r.ok).length; const failed=results.filter((r)=>!r.ok);
  const out={ ok:failed.length===0, version:'83.0.0', generatedAt:new Date().toISOString(), passed, total:results.length, failed:failed.length, results, truth:{ livePaymentProof:false, liveProviderNetworkProof:false, liveNeonPrimaryProof:false, deployedDnsSslProof:false, browserClickAutomationProof:false, retainedLegacyClientModules:true, retainedLegacyClientModulesReason:'Current index.html depends on historical client modules; old proof/state/docs were pruned and claims were corrected.' } };
  fs.mkdirSync(path.join(ROOT,'WHITE_GLOVE_V83'), { recursive:true });
  fs.writeFileSync(path.join(ROOT,'WHITE_GLOVE_V83/smoke_output_v83.json'), JSON.stringify(out,null,2));
  fs.writeFileSync(path.join(ROOT,'WHITE_GLOVE_V83/V83_TRUTH_LEDGER.json'), JSON.stringify({ version:'83.0.0', generatedAt:out.generatedAt, implemented:['clean V83 package pruning of old proof/state/doc residue','strict Neon-primary fails before local fallback write when missing','operational Neon table schema for sessions/events/payments/webhook replay in addition to snapshots','real PayPal OAuth + verify-webhook-signature path when network and credentials are enabled','Stripe and PayPal webhook persistence through the shared persistence layer','production readiness refuses plaintext/bootstrap-only credential posture','static audit explicitly labeled as non-browser-click proof','deployment receipts explicitly local-readiness only','0s mount explicitly manifest-only, not sandbox/process runtime'], notClaimed:['live payment movement','live provider callback proof','live Neon primary proof','deployed DNS/SSL proof','browser click automation proof','full warehouse/driver/navigation operations depth'] }, null, 2));
  console.log(JSON.stringify({ ok:out.ok, passed, total:results.length, failed:failed.length, output:'WHITE_GLOVE_V83/smoke_output_v83.json' }, null, 2));
  if(!out.ok){ console.error(JSON.stringify(failed,null,2)); process.exit(1); }
})();
