[build]
  publish = "."

[[redirects]]
  from = "/events"
  to = "/events.html"
  status = 200

[[redirects]]
  from = "/shop"
  to = "/shop.html"
  status = 200

[[redirects]]
  from = "/event-request"
  to = "/quote.html"
  status = 200

[[redirects]]
  from = "/scan"
  to = "/scan.html"
  status = 200

[[redirects]]
  from = "/preview"
  to = "/preview.html"
  status = 200
