import { canAccessTenantRecord, filterTenantRecords, tenantScopeFromSession } from '../runtime/tenant-scope.mjs';
export const name='cases.routes'; export const area='cases';
export const owns=['case overview','case scoped lists','case editor launches'];
export const routes=['GET /api/v17/cases','GET /api/v17/cases/:id/overview','POST /api/v17/cases/:id/open-in-skye-docx-max'];
export async function handle(ctx){
  const { method, url, sendJSON, readBody, loadCaseRecords, loadDocumentRecords, loadPacketRecords, loadEditorHandoffs, loadEditorReturns, loadCaseNotes, loadCaseArtifacts, session, createSkyeDocxMaxHandoff, writeEditorHandoffPayload, writeJSON, EDITOR_HANDOFF_LOG_FILE, summarizeSkyeDocxHandoff, audit, markdownToHtml }=ctx;
  if(method==='GET' && url.pathname==='/api/v17/cases'){ const rows=filterTenantRecords(session, await loadCaseRecords()); return sendJSON(200,{ok:true,scope:tenantScopeFromSession(session),count:rows.length,items:rows.map(row=>({id:row.id,title:row.title,status:row.status,updatedAt:row.updatedAt,documentCount:row.documentIds?.length||0,packetId:row.packetId||null,handoffId:row.handoffId||null,owner:row.owner,tenant:row.tenant||null}))}); }
  const overview=url.pathname.match(/^\/api\/v17\/cases\/([^/]+)\/overview$/);
  if(method==='GET' && overview){ const id=decodeURIComponent(overview[1]); const cases=await loadCaseRecords(); const c=cases.find(row=>row.id===id); if(!c) return sendJSON(404,{ok:false,error:'case not found'}); if(!canAccessTenantRecord(session,c)) return sendJSON(403,{ok:false,error:'You do not have access to this case.'}); const [docs,packets,handoffs,returns,notes,artifacts]=await Promise.all([loadDocumentRecords(),loadPacketRecords(),loadEditorHandoffs(),loadEditorReturns(),loadCaseNotes(),loadCaseArtifacts()]); const docSet=docs.filter(d=>(c.documentIds||[]).includes(d.id)||d.caseId===c.id); const packet=packets.find(p=>p.id===c.packetId)||null; return sendJSON(200,{ok:true,case:c,documents:docSet,packet,handoffs:handoffs.filter(h=>h.id===c.handoffId||h.metadata?.caseId===c.id),returns:returns.filter(r=>r.metadata?.caseId===c.id || (c.returnIds||[]).includes(r.id)),notes:notes.filter(n=>n.caseId===c.id),artifacts:artifacts.filter(a=>a.caseId===c.id),actions:[{id:'open_skye_docx_max',label:'Open in SkyeDocx Max',method:'POST',href:`/api/v17/cases/${encodeURIComponent(id)}/open-in-skye-docx-max`},{id:'client_status',label:'View client status',href:`/api/cases/${encodeURIComponent(id)}/client-status`},{id:'partner_packet',label:'Export partner packet',href:`/api/cases/${encodeURIComponent(id)}/partner-packet`}]}); }
  const open=url.pathname.match(/^\/api\/v17\/cases\/([^/]+)\/open-in-skye-docx-max$/);
  if(method==='POST' && open){ const id=decodeURIComponent(open[1]); const body=await readBody(); const cases=await loadCaseRecords(); const c=cases.find(row=>row.id===id); if(!c) return sendJSON(404,{ok:false,error:'case not found'}); if(!canAccessTenantRecord(session,c)) return sendJSON(403,{ok:false,error:'You do not have access to this case.'}); const docs=await loadDocumentRecords(); const caseDocs=docs.filter(d=>(c.documentIds||[]).includes(d.id)||d.caseId===c.id); const markdown = body.markdown || [`# ${c.title}`, '', `Case ID: ${c.id}`, '', ...caseDocs.map(d=>`## ${d.title||d.templateTitle||d.templateId}\nStatus: ${d.status}\nRisk: ${d.riskLevel||'unknown'}`)].join('\n'); const handoff=createSkyeDocxMaxHandoff({title:c.title,markdown,html:markdownToHtml(markdown),metadata:{caseId:c.id,caseStatus:c.status,caseType:c.caseType,documentIds:c.documentIds||[],packetId:c.packetId||null,source:'v17-case-overview-open',templateMetadata:caseDocs.map(d=>({templateId:d.templateId,title:d.templateTitle||d.title,riskLevel:d.riskLevel,jurisdiction:d.jurisdiction,status:d.status}))},session}); await writeEditorHandoffPayload(handoff); const rows=await loadEditorHandoffs(); rows.unshift(summarizeSkyeDocxHandoff(handoff)); await writeJSON(EDITOR_HANDOFF_LOG_FILE,rows.slice(0,20000)); const event=await audit('v17_case_opened_in_skye_docx_max',{caseId:c.id,handoffId:handoff.id},ctx.req); return sendJSON(201,{ok:true,handoff:summarizeSkyeDocxHandoff(handoff),launchUrl:handoff.launchUrl,auditId:event.id}); }
  return {handled:false};
}
