
(function(){
  const lanes={lead:['Celeste Monroe Revenue Brain','Marcus Vale Operations Review'],client:['Adrian Cross Client Success Brain','Victor Saint QA Review'],candidate:['Sienna Brooks Staffing Brain','Naomi Sterling Finance Review'],vendor:['Helena Ward Vendor Brain','Julian Mercer Compliance Review'],compliance:['Julian Mercer Compliance Brain','Gray London Skyes Founder Review'],proof:['Victor Saint QA Brain','Site Operator Brain'],finance:['Naomi Sterling Finance Brain','Marcus Vale Operations Review'],technology:['Orion Hayes Technology Brain','Site Operator Brain'],marketing:['Valentina Reyes Brand Brain','Celeste Monroe Revenue Review'],government:['Donovan Pierce Gov/Enterprise Brain','Julian Mercer Compliance Review'],founder:['Gray London Skyes Founder Brain','Site Operator Brain'],general:['Site Operator Brain','Central Company Command Brain']};
  function classify(text){text=(text||'').toLowerCase(); if(/lead|prospect|deal|close|quote|price|proposal|pipeline/.test(text))return'lead'; if(/client|complaint|renewal|onboard|launch|status/.test(text))return'client'; if(/candidate|resume|worker|staff|placement|recruit/.test(text))return'candidate'; if(/vendor|partner|subcontractor|supplier/.test(text))return'vendor'; if(/compliance|legal|contract|insurance|license|risk/.test(text))return'compliance'; if(/proof|qa|receipt|audit|claim|verify/.test(text))return'proof'; if(/invoice|billing|payroll|margin|budget|commission/.test(text))return'finance'; if(/website|worker|cloudflare|api|database|brain|automation|technical/.test(text))return'technology'; if(/brand|seo|blog|copy|campaign|marketing/.test(text))return'marketing'; if(/sam|government|procurement|rfp|bid|naics|contracting/.test(text))return'government'; if(/founder|gray|approval|override|ownership/.test(text))return'founder'; return'general'}
  async function sendBridgeReceipt(receipt){try{const res=await fetch('/api/0s-command-bridge/events',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({source_app:'nexus',source_surface:'nexus-crm-records',event_type:'nexus.crm_record_created',summary:receipt.note||`NEXUS ${receipt.lane} receipt`,entity:{kind:'crm-receipt',id:receipt.id,label:receipt.lane},crm:{stage:receipt.status,owner:receipt.primary_brain},ids:{receipt_id:receipt.id},metadata:{secondary_review:receipt.secondary_review,recommended_next_actions:receipt.recommended_next_actions.join(' | ')}})});return await res.json().catch(()=>({ok:res.ok,status:res.status}))}catch(e){return{ok:false,error:e.message||'bridge_unavailable'}}}
  function makeReceipt(source){const input=document.querySelector(source); const out=document.querySelector('#nexus-output'); const text=input?input.value:''; const lane=classify(text); const pair=lanes[lane]||lanes.general; const obj={id:'NEXUS-'+Date.now(),created_at:new Date().toISOString(),lane,primary_brain:pair[0],secondary_review:pair[1],status:'draft-local-receipt',recommended_next_actions:['Capture source message','Assign human owner','Request missing facts','Generate proof receipt if public claim is affected','Escalate to founder approval if authority, money, legal, or public representation changes'],note:text}; localStorage.setItem(obj.id,JSON.stringify(obj)); if(out)out.textContent=JSON.stringify({...obj,command_bridge:'saving'},null,2); sendBridgeReceipt(obj).then(bridge=>{if(out)out.textContent=JSON.stringify({...obj,command_bridge:bridge},null,2)})}
  window.nexusRoute=function(sel){makeReceipt(sel||'#nexus-input')};
  window.nexusExport=function(){const rows=[]; for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i); if(k&&k.startsWith('NEXUS-')){try{rows.push(JSON.parse(localStorage.getItem(k)))}catch(e){}}} const blob=new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='nexus-local-ledger.json'; a.click();};
  window.nexusClear=function(){Object.keys(localStorage).filter(k=>k.startsWith('NEXUS-')).forEach(k=>localStorage.removeItem(k)); const out=document.querySelector('#nexus-output'); if(out)out.textContent='Local NEXUS ledger cleared.'};
})();
