name = "skyegatefs27-citadeldb"
main = "cloudflare/worker.mjs"
compatibility_date = "2026-05-15"
compatibility_flags = ["nodejs_compat"]
keep_vars = true
workers_dev = true

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = true

[observability]
enabled = true
