apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: citadeldb-nightly-backup
  namespace: citadeldb
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: citadeldb-ha
