apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: citadeldb-pooler-rw
  namespace: citadeldb
spec:
  cluster:
    name: citadeldb-ha
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "30"
