const text = (v = '') => String(v || '').trim();
const num = (v, f = 0) => Number.isFinite(Number(v)) ? Math.trunc(Number(v)) : f;
const bool = (v, f = false) => v === undefined || v === null || v === '' ? f : v === true || v === 'true' || v === '1' || v === 1;
const asJson = (v, f) => Array.isArray(v) || (v && typeof v === 'object') ? v : (() => { try { return JSON.parse(v || ''); } catch { return f; } })();
export function normalizeRefundItemInput(item = {}) { const quantity = Math.max(1, num(item.quantity, 1)); const amountCents = Math.max(0, num(item.amountCents ?? item.amount_cents ?? item.lineTotalCents ?? item.line_total_cents, 0)); return { productId: text(item.productId || item.product_id), variantId: text(item.variantId || item.variant_id), orderItemId: text(item.orderItemId || item.order_item_id), quantity, amountCents, restock: bool(item.restock, true), reason: text(item.reason) }; }
export function normalizeRefundRequestInput(body = {}, order = {}) { const items = asJson(body.items, body.items || []).map(normalizeRefundItemInput).filter((i) => i.amountCents > 0 || i.productId || i.orderItemId); const itemAmount = items.reduce((sum, i) => sum + Number(i.amountCents || 0), 0); const fallback = Math.max(0, num(body.amountCents ?? body.amount_cents, 0)); const max = Math.max(0, Number(order.totalCents ?? order.total_cents ?? 0)); const amountCents = Math.min(max || (itemAmount || fallback), itemAmount || fallback); return { orderId: text(body.orderId || order.id), amountCents, reason: text(body.reason || 'merchant_refund'), provider: text(body.provider || 'manual'), providerRef: text(body.providerRef || body.provider_ref), status: text(body.status || 'pending').toLowerCase(), note: text(body.note), restock: bool(body.restock, true), items }; }
export function buildRefundPreview(order = {}, priorRefunds = [], request = {}) { const paidCents = Math.max(0, Number(order.totalCents ?? order.total_cents ?? 0)); const refundedCents = (Array.isArray(priorRefunds) ? priorRefunds : []).filter((r) => !['voided', 'failed'].includes(String(r.status || '').toLowerCase())).reduce((sum, r) => sum + Number(r.amountCents ?? r.amount_cents ?? 0), 0); const availableCents = Math.max(0, paidCents - refundedCents); const requestedCents = Math.max(0, Number(request.amountCents ?? request.amount_cents ?? 0)); const approvedCents = Math.min(availableCents, requestedCents); return { paidCents, refundedCents, availableCents, requestedCents, approvedCents, completeRefund: paidCents > 0 && approvedCents >= availableCents, valid: approvedCents > 0 && approvedCents === requestedCents };
}
export function refundRecord(row) { if (!row) return null; let items = []; try { items = JSON.parse(row.items_json || row.items || '[]'); } catch {} return { id: row.id || '', merchantId: row.merchant_id || row.merchantId || '', orderId: row.order_id || row.orderId || '', refundNumber: row.refund_number || row.refundNumber || '', amountCents: Number(row.amount_cents ?? row.amountCents ?? 0), currency: row.currency || 'USD', provider: row.provider || 'manual', providerRef: row.provider_ref || row.providerRef || '', reason: row.reason || '', status: row.status || 'pending', note: row.note || '', restock: Boolean(Number(row.restock ?? 1)), items, createdAt: row.created_at || row.createdAt || '', updatedAt: row.updated_at || row.updatedAt || '' }; }
