(function () {
  const STORAGE_KEY = 'skyewebcreatormax.projects.v1';
  const DELIVERY_KEY = 'skyewebcreatormax.delivery.v1';
  const FILE_KEY = 'skyewebcreatormax.files.v1';

  const logEl = document.getElementById('eventLog');
  const projectList = document.getElementById('projectList');
  const deliveryList = document.getElementById('deliveryList');
  const editorTabs = document.getElementById('editorTabs');
  const editor = document.getElementById('codeEditor');
  const preview = document.getElementById('previewFrame');
  const connectionState = document.getElementById('connectionState');
  const gatePill = document.getElementById('gatePill');
  const templateSearch = document.getElementById('templateSearch');
  const templateList = document.getElementById('templateList');
  const templateSourceRefs = document.getElementById('templateSourceRefs');
  const qualityGrid = document.getElementById('qualityGrid');
  const runtimeState = document.getElementById('runtimeState');
  const reviewCounts = document.getElementById('reviewCounts');
  const executionCounts = document.getElementById('executionCounts');
  const dispatchCounts = document.getElementById('dispatchCounts');
  const workflowCounts = document.getElementById('workflowCounts');
  const deliveryLabel = document.getElementById('deliveryLabel');
  const reviewOwner = document.getElementById('reviewOwner');
  const reviewStatus = document.getElementById('reviewStatus');
  const reviewCheckpoint = document.getElementById('reviewCheckpoint');
  const deliveryNotes = document.getElementById('deliveryNotes');
  const donorTemplates = window.SkyeWebCreatorTemplates;

  let activeFile = 'index.html';
  let selectedTemplateId = donorTemplates?.all?.[0]?.id || 'starter-fallback';
  let runtimeOnline = false;

  const starterFiles = {
    'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Generated by SkyeWebCreatorMax | Premium Client Platform</title>
    <link rel="stylesheet" href="./styles.css">
  </head>
  <body>
    <canvas id="scene" aria-hidden="true"></canvas>
    <main>
      <nav class="nav">
        <strong>Client Growth Platform</strong>
        <div><a href="#work">Work</a><a href="#pricing">Pricing</a><a class="cta" href="#contact">Start</a></div>
      </nav>
      <section class="hero">
        <div>
          <p class="eyebrow">SkyDexia design vault build</p>
          <h1>Launch an enterprise-grade client experience with motion, depth, and conversion baked in.</h1>
          <p class="lead">Generated from the SkyeWebCreatorMax stack: Three.js-ready hero layer, premium responsive UI, editable source files, SkyeGateFS13 routing, and AE delivery metadata.</p>
          <div class="actions"><a class="cta" href="#contact">Book the build</a><a class="ghost" href="#work">See the system</a></div>
        </div>
        <aside class="product-card" aria-label="Generated product interface mockup">
          <div class="window"><span></span><span></span><span></span></div>
          <div class="metric"><b>$4.8M</b><small>pipeline influenced</small></div>
          <div class="chart"><i></i><i></i><i></i><i></i></div>
          <div class="rows"><span></span><span></span><span></span></div>
        </aside>
      </section>
      <section class="proof" id="work">
        <article><b>3D Hero</b><span>WebGL scene, fallback canvas, cinematic product framing.</span></article>
        <article><b>SaaS UI</b><span>Dashboard sections, cards, pricing, onboarding, admin flows.</span></article>
        <article><b>Delivery</b><span>Packaged source, preview, persistence, and AE handoff.</span></article>
      </section>
    </main>
    <script src="./app.js"></script>
  </body>
</html>`,
    'styles.css': `:root{color-scheme:dark;--green:#39ff88;--cyan:#5df1ff;--plasma:#ff4fd8;--coral:#ff6b8f;--bg:#030805;--ink:#f4fff7;--muted:#adc7b9;--line:rgba(139,255,188,.2)}
*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#030805;color:var(--ink);overflow-x:hidden}
#scene{position:fixed;inset:0;width:100%;height:100%;z-index:0;background:radial-gradient(circle at 25% 16%,rgba(57,255,136,.28),transparent 30%),radial-gradient(circle at 76% 18%,rgba(255,79,216,.2),transparent 28%),linear-gradient(145deg,#030805,#061511 56%,#151026)}
main{position:relative;z-index:1}.nav{display:flex;justify-content:space-between;align-items:center;gap:18px;padding:22px clamp(18px,5vw,64px);background:rgba(3,8,5,.42);backdrop-filter:blur(18px);border-bottom:1px solid rgba(255,255,255,.08)}
.nav div{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.nav a{color:var(--muted);text-decoration:none;font-weight:800}.cta{display:inline-flex;align-items:center;justify-content:center;min-height:42px;border-radius:8px;padding:10px 15px;background:linear-gradient(135deg,var(--green),var(--cyan));color:#021007!important;text-decoration:none;font-weight:950;box-shadow:0 0 42px rgba(57,255,136,.32)}
.hero{min-height:calc(100vh - 86px);display:grid;grid-template-columns:minmax(0,1fr) minmax(320px,520px);gap:clamp(24px,5vw,74px);align-items:center;padding:clamp(32px,6vw,82px)}
.eyebrow{margin:0 0 16px;color:var(--green);font-size:12px;font-weight:950;text-transform:uppercase;letter-spacing:.16em}
h1{max-width:980px;margin:0;font-size:clamp(48px,7.6vw,118px);line-height:.84;letter-spacing:0}.lead{max-width:760px;margin:24px 0 0;color:var(--muted);font-size:clamp(18px,2vw,24px);line-height:1.42}
.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:30px}.ghost{display:inline-flex;align-items:center;justify-content:center;min-height:42px;border:1px solid rgba(255,255,255,.18);border-radius:8px;padding:10px 15px;background:rgba(255,255,255,.06);color:var(--ink);text-decoration:none;font-weight:900}
.product-card{border:1px solid var(--line);border-radius:8px;background:linear-gradient(145deg,rgba(9,24,17,.84),rgba(17,13,34,.76));box-shadow:0 34px 120px rgba(0,0,0,.55),0 0 90px rgba(57,255,136,.13);backdrop-filter:blur(22px);overflow:hidden;transform:perspective(1100px) rotateY(-12deg) rotateX(4deg);animation:float 4.8s ease-in-out infinite}
@keyframes float{50%{transform:perspective(1100px) rotateY(-7deg) rotateX(2deg) translateY(-12px)}}.window{display:flex;gap:7px;padding:13px;border-bottom:1px solid rgba(139,255,188,.18)}.window span{width:10px;height:10px;border-radius:50%;background:var(--coral)}.window span:nth-child(2){background:var(--green)}.window span:nth-child(3){background:var(--cyan)}
.metric{padding:22px}.metric b{display:block;font-size:clamp(46px,7vw,84px);line-height:.86;color:var(--green)}.metric small{color:var(--muted);font-weight:800;text-transform:uppercase;letter-spacing:.12em}.chart{height:180px;margin:0 22px 22px;display:flex;align-items:end;gap:12px}.chart i{flex:1;border-radius:8px 8px 0 0;background:linear-gradient(to top,var(--green),var(--plasma));box-shadow:0 0 28px rgba(57,255,136,.22)}.chart i:nth-child(1){height:46%}.chart i:nth-child(2){height:76%}.chart i:nth-child(3){height:58%}.chart i:nth-child(4){height:92%}.rows{display:grid;gap:10px;padding:0 22px 22px}.rows span{height:10px;border-radius:999px;background:rgba(255,255,255,.13)}.rows span:nth-child(1){width:86%;background:rgba(93,241,255,.38)}.rows span:nth-child(2){width:68%}.rows span:nth-child(3){width:78%;background:rgba(255,79,216,.3)}
.proof{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;padding:0 clamp(18px,6vw,82px) 60px}.proof article{min-height:180px;border:1px solid var(--line);border-radius:8px;padding:20px;background:rgba(255,255,255,.06);backdrop-filter:blur(18px)}.proof b{display:block;color:var(--green);font-size:20px;margin-bottom:10px}.proof span{color:var(--muted);line-height:1.45}
@media(max-width:900px){.hero{grid-template-columns:1fr}.product-card{transform:none}.proof{grid-template-columns:1fr}}@media(max-width:560px){.nav{align-items:flex-start;flex-direction:column}h1{font-size:48px}}`,
    'app.js': `const canvas = document.getElementById('scene');
const ctx = canvas.getContext('2d');
const dots = Array.from({length:92},(_,i)=>({seed:i*17.17,r:80+(i%9)*26,s:.00025+(i%6)*.00006,z:1+(i%4)}));
function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
function draw(t){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.globalCompositeOperation='lighter';dots.forEach(dot=>{const a=t*dot.s+dot.seed;const x=innerWidth*.62+Math.cos(a*1.8)*dot.r+Math.sin(a*.7)*120;const y=innerHeight*.45+Math.sin(a*1.25)*dot.r*.56;const g=ctx.createRadialGradient(x,y,0,x,y,dot.z*16);g.addColorStop(0,'rgba(57,255,136,.72)');g.addColorStop(.5,'rgba(93,241,255,.2)');g.addColorStop(1,'rgba(255,79,216,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,dot.z*16,0,Math.PI*2);ctx.fill()});ctx.globalCompositeOperation='source-over';requestAnimationFrame(draw)}
addEventListener('resize',resize);resize();requestAnimationFrame(draw);
console.log('SkyeWebCreatorMax premium artifact booted');`,
    'README.md': `# Generated Website Package

Created in SkyeWebCreatorMax.

Includes:
- cinematic animated hero layer
- premium responsive source
- editable files and live preview
- SkyeGateFS13 event mirror path
- AE delivery handoff metadata
`,
  };

  function load(key, fallback) {
    try { return JSON.parse(localStorage.getItem(key) || ''); } catch { return fallback; }
  }

  function save(key, value) {
    localStorage.setItem(key, JSON.stringify(value));
  }

  function id(prefix) {
    return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
  }

  function escapeHtml(value) {
    return String(value)
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;');
  }

  function log(message, payload) {
    const line = `[${new Date().toISOString()}] ${message}${payload ? `\n${JSON.stringify(payload, null, 2)}` : ''}`;
    logEl.textContent = `${line}\n\n${logEl.textContent}`.trim();
  }

  function files() {
    const current = load(FILE_KEY, null);
    if (current && Object.keys(current).length) return current;
    const template = selectedTemplate();
    const initialFiles = template?.files || starterFiles;
    save(FILE_KEY, initialFiles);
    return { ...initialFiles };
  }

  function setFiles(next) {
    save(FILE_KEY, next);
  }

  function selectedTemplate() {
    return donorTemplates?.byId?.(selectedTemplateId) || donorTemplates?.all?.[0] || null;
  }

  async function loadTemplateFiles(template) {
    if (template?.files) return { ...template.files };
    if (!template?.exportPath) return null;
    const entries = await Promise.all(['index.html', 'styles.css', 'app.js', 'README.md'].map(async (file) => {
      const response = await fetch(`${template.exportPath}/${file}`);
      if (!response.ok) throw new Error(`Unable to load ${template.exportPath}/${file}`);
      return [file, await response.text()];
    }));
    return Object.fromEntries(entries);
  }

  async function applyTemplate(template, reason = 'manual') {
    const templateFiles = await loadTemplateFiles(template);
    if (!templateFiles) {
      log('Template is reference-only and cannot generate until upgraded to SOLE/SkyeSol floor', { templateId: template?.id });
      return;
    }
    selectedTemplateId = template.id;
    activeFile = 'index.html';
    setFiles(templateFiles);
    renderTemplateList();
    renderTabs();
    renderPreview();
    renderProjects();
    log('Applied donor-backed template to editable source', {
      reason,
      templateId: template.id,
      templateName: template.name,
      sourceRefs: template.sourceRefs,
      stack: template.stack,
      qualityTier: template.qualityTier,
    });
  }

  function renderTemplateList() {
    if (!templateList || !donorTemplates?.all) return;
    const query = String(templateSearch?.value || '').toLowerCase().trim();
    const templates = donorTemplates.all.filter((template) => {
      const haystack = [
        template.id,
        template.name,
        ...(template.aliases || []),
        ...(template.stack || []),
        ...(template.useCases || []),
        ...(template.sourceRefs || []),
      ].join(' ').toLowerCase();
      return !query || haystack.includes(query);
    });
    templateList.innerHTML = templates.map((template) => `
      <button type="button" class="template-option ${template.id === selectedTemplateId ? 'active' : ''}" data-template-id="${escapeHtml(template.id)}">
        <b>${escapeHtml(template.name)}</b>
        <small>${template.enabledForGeneration === false ? 'REFERENCE ONLY - blocked from generation until upgraded to the SOLE/SkyeSol floor. ' : ''}${escapeHtml((template.stack || []).join(' + '))}</small>
      </button>
    `).join('') || '<article class="card"><strong>No donor templates found</strong><small>Try shadcn, TailGrids, R3F, drei, Triplex, dashboard, landing, or 3D.</small></article>';
    const template = selectedTemplate();
    templateSourceRefs.innerHTML = template ? [
      '<strong>Selected donor source refs</strong>',
      ...(template.sourceRefs || []).map((ref) => `<code>${escapeHtml(ref)}</code>`),
    ].join('') : '';
  }

  function renderTabs() {
    const all = files();
    editorTabs.innerHTML = Object.keys(all).map((file) => (
      `<button type="button" class="${file === activeFile ? 'active' : ''}" data-file="${file}">${file}</button>`
    )).join('');
    editor.value = all[activeFile] || '';
  }

  function applyEditor() {
    const all = files();
    all[activeFile] = editor.value;
    setFiles(all);
    renderPreview();
    renderProjects();
    log('Applied editor changes to live preview', { file: activeFile });
  }

  function renderPreview() {
    const all = files();
    const html = (all['index.html'] || '')
      .replace('<link rel="stylesheet" href="./styles.css">', `<style>${all['styles.css'] || ''}</style>`)
      .replace('<script src="./app.js"></script>', `<script>${all['app.js'] || ''}<\/script>`);
    preview.srcdoc = html;
    renderQualityAudit(all);
  }

  function countMatches(value, pattern) {
    return (String(value).match(pattern) || []).length;
  }

  function renderQualityAudit(all) {
    if (!qualityGrid) return;
    const html = all['index.html'] || '';
    const css = all['styles.css'] || '';
    const js = all['app.js'] || '';
    const template = selectedTemplate();
    const metrics = [
      ['Tier', template?.qualityTier === 'house-standard' ? 'PASS' : 'BLOCK', template?.qualityTier || 'unknown'],
      ['Body', html.length > 9000 ? 'PASS' : 'RAISE', `${html.length} chars / 9000 floor`],
      ['Panels', countMatches(html, /class="[^"]*(panel|card|tile|stack)[^"]*"/g) >= 10 ? 'PASS' : 'RAISE', `${countMatches(html, /class="[^"]*(panel|card|tile|stack)[^"]*"/g)} surfaces`],
      ['Controls', countMatches(html, /<(button|input|select|textarea)\b/g) >= 10 ? 'PASS' : 'RAISE', `${countMatches(html, /<(button|input|select|textarea)\b/g)} controls`],
      ['Motion', /(requestAnimationFrame|@keyframes|transition)/.test(`${css}\n${js}`) ? 'PASS' : 'RAISE', 'animation/canvas required'],
      ['Gate', /gate|portal|intake|form/i.test(html) ? 'PASS' : 'RAISE', 'portal or intake path'],
    ];
    qualityGrid.innerHTML = metrics.map(([label, score, detail]) => `
      <article>
        <b>${escapeHtml(score)}</b>
        <span>${escapeHtml(label)} · ${escapeHtml(detail)}</span>
      </article>
    `).join('');
  }

  function renderProjects() {
    const projects = load(STORAGE_KEY, []);
    const all = files();
    projectList.innerHTML = [
      ...projects.map((project) => `
        <article class="card">
          <strong>${project.name}</strong>
          <small>${project.buildType} · ${project.status} · ${project.createdAt}</small>
        </article>
      `),
      `<article class="card"><strong>Editable source files</strong><small>${Object.keys(all).join(', ')}</small></article>`,
    ].join('');
  }

  function renderDeliveries() {
    const deliveries = load(DELIVERY_KEY, []);
    deliveryList.innerHTML = deliveries.length ? deliveries.map((delivery) => `
      <article class="card">
        <strong>${delivery.projectName}</strong>
        <small>${delivery.status} · ${delivery.target} · ${delivery.createdAt}</small>
        ${delivery.review ? `<small>review: ${escapeHtml(delivery.review.status)}${delivery.review.owner ? ` · ${escapeHtml(delivery.review.owner)}` : ''}${delivery.review.checkpoint ? ` · ${escapeHtml(delivery.review.checkpoint)}` : ''}</small>` : ''}
        ${delivery.execution ? `<small>execution: ${escapeHtml(delivery.execution.status)}${delivery.execution.owner ? ` · ${escapeHtml(delivery.execution.owner)}` : ''}${delivery.execution.checkpoint ? ` · ${escapeHtml(delivery.execution.checkpoint)}` : ''}</small>` : ''}
      </article>
    `).join('') : '<article class="card"><strong>No AE packages queued</strong><small>Create or package an artifact to send it toward AE CommandHub.</small></article>';
  }

  async function postRuntime(path, body) {
    const response = await fetch(path, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(body || {}),
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.error || `runtime request failed (${response.status})`);
    return data;
  }

  async function fetchRuntime(path) {
    const response = await fetch(path);
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.error || `runtime request failed (${response.status})`);
    return data;
  }

  function syncLocalDeliveryFromRuntime(item) {
    const deliveries = load(DELIVERY_KEY, []);
    const next = [
      {
        id: item.id,
        projectId: item.projectId,
        projectName: item.projectName,
        status: item.review?.status || 'queued-for-ae-delivery',
        target: item.target,
        createdAt: item.createdAt,
        review: item.review,
        execution: item.execution,
      },
      ...deliveries.filter((entry) => entry.id !== item.id),
    ];
    save(DELIVERY_KEY, next);
    renderDeliveries();
  }

  function renderBoardSummary(summary = {}) {
    reviewCounts.textContent = `draft ${summary.draft || 0} · ready ${summary.ready || 0} · approved ${summary.approved || 0} · blocked ${summary.blocked || 0} · dispatched ${summary.dispatched || 0}`;
  }

  function renderExecutionSummary(summary = {}) {
    executionCounts.textContent = `queued ${summary.queued || 0} · active ${summary.active || 0} · fulfilled ${summary.fulfilled || 0} · blocked ${summary.blocked || 0}`;
  }

  function renderDispatchSummary(summary = {}) {
    if (!dispatchCounts) return;
    dispatchCounts.textContent = `queued ${summary.queued || 0} · active ${summary.active || 0} · delivered ${summary.delivered || 0} · blocked ${summary.blocked || 0}`;
  }

  function renderWorkflowSummary(summary = {}) {
    if (!workflowCounts) return;
    workflowCounts.textContent = `archive ${summary.archive || 0} · review ${summary.review || 0} · execution ${summary.execution || 0} · dispatch ${summary.dispatch || 0}`;
  }

  async function refreshRuntimeBoard() {
    if (location.protocol === 'file:') {
      runtimeOnline = false;
      runtimeState.textContent = 'Runtime unavailable on file://';
      renderBoardSummary({});
      renderExecutionSummary({});
      renderDispatchSummary({});
      renderWorkflowSummary({});
      return false;
    }
    try {
      const [status, board, timeline] = await Promise.all([
        fetchRuntime('/api/runtime/status'),
        fetchRuntime('/api/runtime/delivery-board'),
        fetchRuntime('/api/runtime/workflow-timeline'),
      ]);
      runtimeOnline = true;
      runtimeState.textContent = `Runtime online · ${status.deliveryPacks} packs`;
      renderBoardSummary(board.summary || {});
      renderExecutionSummary(board.executionSummary || status.executionBoard || {});
      renderDispatchSummary(board.dispatchSummary || status.dispatchBoard || {});
      renderWorkflowSummary(timeline.workflowTimeline?.summary || status.workflowTimeline || {});
      (board.items || []).forEach(syncLocalDeliveryFromRuntime);
      return true;
    } catch (error) {
      runtimeOnline = false;
      runtimeState.textContent = 'Runtime offline';
      renderBoardSummary({});
      renderExecutionSummary({});
      renderDispatchSummary({});
      renderWorkflowSummary({});
      log('SkyeWebCreatorMax runtime board unavailable', { error: error.message });
      return false;
    }
  }

  async function createProject(formData) {
    const buildType = formData.get('buildType');
    const selected = selectedTemplate();
    const template = selected?.enabledForGeneration === false ? donorTemplates?.forBuildType?.(buildType) : selected || donorTemplates?.forBuildType?.(buildType);
    if (template) await applyTemplate(template, 'project-create');
    const project = {
      id: id('swc'),
      name: formData.get('name'),
      buildType,
      aiLane: formData.get('aiLane'),
      brief: formData.get('brief'),
      pages: String(formData.get('pages') || '').split(',').map((x) => x.trim()).filter(Boolean),
      features: String(formData.get('features') || '').split(',').map((x) => x.trim()).filter(Boolean),
      status: 'requested',
      designVault: 'design-vault/library',
      gateway: 'SkyeGateFS13',
      donorTemplate: template ? {
        id: template.id,
        name: template.name,
        stack: template.stack,
        sourceRefs: template.sourceRefs,
        qualityTier: template.qualityTier,
      } : null,
      targetPlatforms: ['skydexia', 'ae-commandhub'],
      createdAt: new Date().toISOString(),
    };
    const projects = load(STORAGE_KEY, []);
    projects.unshift(project);
    save(STORAGE_KEY, projects);
    log('Created SkyeGateFS13-routed project request', project);
    renderProjects();
    return project;
  }

  async function packageArtifact(project) {
    const all = files();
    const artifact = {
      id: id('artifact'),
      projectId: project.id,
      projectName: project.name,
      status: 'queued-for-ae-delivery',
      target: 'ae-commandhub',
      files: Object.keys(all),
      sourceSnapshot: all,
      createdAt: new Date().toISOString(),
    };
    const deliveries = load(DELIVERY_KEY, []);
    deliveries.unshift(artifact);
    save(DELIVERY_KEY, deliveries);
    log('Queued generated website package for AE handoff', artifact);
    renderDeliveries();
    if (location.protocol !== 'file:') {
      try {
        const runtimePack = await postRuntime('/api/runtime/delivery-packs', {
          projectId: project.id,
          projectName: project.name,
          label: deliveryLabel?.value?.trim() || `${project.name} delivery pack`,
          target: artifact.target,
          notes: deliveryNotes?.value?.trim() || '',
          sourceSnapshot: all,
          review: {
            owner: reviewOwner?.value?.trim() || '',
            status: reviewStatus?.value || 'draft',
            checkpoint: reviewCheckpoint?.value?.trim() || '',
            notes: deliveryNotes?.value?.trim() || '',
          },
        });
        syncLocalDeliveryFromRuntime(runtimePack.item);
        await refreshRuntimeBoard();
        log('Archived delivery pack in same-folder runtime', runtimePack.item);
      } catch (error) {
        log('Local runtime archive skipped', { error: error.message });
      }
    }
    return artifact;
  }

  async function mirrorGateEvent(type, meta) {
    if (!window.SkyeGateFS13Client) {
      log('SkyeGateFS13 client is not loaded');
      return;
    }
    const result = await window.SkyeGateFS13Client.mirrorEvent({
      type,
      meta,
      actor: 'standalone-user',
      ws_id: meta?.projectId || 'standalone-webcreator',
    });
    log('SkyeGateFS13 mirror attempt completed', result);
    connectionState.textContent = result.ok ? 'Gateway mirror accepted' : 'Gateway vars/config needed';
    gatePill.textContent = result.ok ? 'GateFS13 connected' : 'GateFS13 vars needed';
  }

  async function askAI() {
    const projects = load(STORAGE_KEY, []);
    const project = projects[0] || await createProject(new FormData(document.getElementById('projectForm')));
    if (!window.SkyeGateFS13Client) {
      log('AI gateway client missing');
      return;
    }
    const response = await window.SkyeGateFS13Client.askAI({
      prompt: `Use SkyDexia and the design vault to improve this website/UI project: ${project.brief}`,
      project,
      files: files(),
    });
    log('AI gateway request completed', response);
  }

  document.getElementById('projectForm').addEventListener('submit', async (event) => {
    event.preventDefault();
    const project = await createProject(new FormData(event.currentTarget));
    mirrorGateEvent('webcreator.project.requested', {
      projectId: project.id,
      app: 'SkyeWebCreatorMax',
      aiLane: project.aiLane,
      billable: true,
    });
  });

  editorTabs.addEventListener('click', (event) => {
    const button = event.target.closest('button[data-file]');
    if (!button) return;
    applyEditor();
    activeFile = button.dataset.file;
    renderTabs();
  });

  templateList?.addEventListener('click', (event) => {
    const button = event.target.closest('button[data-template-id]');
    if (!button) return;
    selectedTemplateId = button.dataset.templateId;
    renderTemplateList();
  });
  templateSearch?.addEventListener('input', renderTemplateList);
  document.getElementById('applyTemplate')?.addEventListener('click', async () => {
    const template = selectedTemplate();
    if (template) await applyTemplate(template);
  });

  document.getElementById('applyEditor').addEventListener('click', applyEditor);
  document.getElementById('packageArtifact').addEventListener('click', async () => {
    applyEditor();
    const projects = load(STORAGE_KEY, []);
    const project = projects[0] || {
      id: id('swc'),
      name: 'Unrequested Local Package',
      buildType: 'local-export',
      status: 'generated',
      createdAt: new Date().toISOString(),
    };
    project.status = 'generated';
    save(STORAGE_KEY, [project, ...projects.filter((item) => item.id !== project.id)]);
    const artifact = await packageArtifact(project);
    mirrorGateEvent('webcreator.delivery.queued', { projectId: project.id, artifactId: artifact.id, billable: true });
    renderProjects();
  });
  document.getElementById('askAI').addEventListener('click', askAI);
  document.getElementById('mirrorGate').addEventListener('click', () => mirrorGateEvent('webcreator.manual.gateway_check', { billable: false }));
  document.getElementById('exportState').addEventListener('click', () => {
    log('Exported local SkyeWebCreatorMax state', {
      projects: load(STORAGE_KEY, []),
      deliveries: load(DELIVERY_KEY, []),
      files: files(),
    });
  });
  document.getElementById('clearState').addEventListener('click', () => {
    localStorage.removeItem(STORAGE_KEY);
    localStorage.removeItem(DELIVERY_KEY);
    localStorage.removeItem(FILE_KEY);
    renderTabs();
    renderPreview();
    renderProjects();
    renderDeliveries();
    log('Cleared local workspace');
  });
  document.getElementById('refreshDeliveryBoard')?.addEventListener('click', () => {
    refreshRuntimeBoard();
  });
  document.getElementById('advanceLatestDelivery')?.addEventListener('click', async () => {
    if (!(await refreshRuntimeBoard())) return;
    try {
      const board = await fetchRuntime('/api/runtime/delivery-packs');
      const latest = board.items?.[0];
      if (!latest) {
        log('No runtime delivery pack is available to advance');
        return;
      }
      const nextStatus = latest.review?.status === 'draft' ? 'ready'
        : latest.review?.status === 'ready' ? 'approved'
        : latest.review?.status === 'approved' ? 'dispatched'
        : 'draft';
      const updated = await postRuntime(`/api/runtime/delivery-packs/${latest.id}/review`, {
        owner: reviewOwner?.value?.trim() || latest.review?.owner || '',
        status: nextStatus,
        checkpoint: reviewCheckpoint?.value?.trim() || 'advanced in local review board',
        notes: deliveryNotes?.value?.trim() || latest.review?.notes || '',
      });
      syncLocalDeliveryFromRuntime(updated.item);
      renderBoardSummary(updated.summary || {});
      log('Advanced latest runtime delivery pack', updated.item);
    } catch (error) {
      log('Failed to advance runtime delivery pack', { error: error.message });
    }
  });
  document.getElementById('queueLatestExecution')?.addEventListener('click', async () => {
    if (!(await refreshRuntimeBoard())) return;
    try {
      const board = await fetchRuntime('/api/runtime/delivery-packs');
      const latest = board.items?.[0];
      if (!latest) {
        log('No runtime delivery pack is available to queue for execution');
        return;
      }
      const nextStatus = latest.execution?.status === 'queued' ? 'active'
        : latest.execution?.status === 'active' ? 'fulfilled'
        : latest.execution?.status === 'fulfilled' ? 'fulfilled'
        : latest.execution?.status === 'blocked' ? 'active'
        : 'queued';
      const updated = await postRuntime(`/api/runtime/delivery-packs/${latest.id}/execution`, {
        owner: reviewOwner?.value?.trim() || latest.execution?.owner || latest.review?.owner || 'ae-operator',
        status: nextStatus,
        checkpoint: reviewCheckpoint?.value?.trim() || 'queued in local execution board',
        notes: deliveryNotes?.value?.trim() || latest.execution?.notes || latest.review?.notes || '',
        targets: latest.targets || latest.execution?.targets || [],
      });
      syncLocalDeliveryFromRuntime(updated.item);
      renderExecutionSummary(updated.summary || {});
      log('Queued latest runtime delivery pack for execution', updated.item);
    } catch (error) {
      log('Failed to queue runtime delivery pack for execution', { error: error.message });
    }
  });
  document.getElementById('dispatchLatestDelivery')?.addEventListener('click', async () => {
    if (!(await refreshRuntimeBoard())) return;
    try {
      const board = await fetchRuntime('/api/runtime/delivery-packs');
      const latest = board.items?.[0];
      if (!latest) {
        log('No runtime delivery pack is available to dispatch');
        return;
      }
      const nextStatus = latest.dispatch?.status === 'queued' ? 'active'
        : latest.dispatch?.status === 'active' ? 'delivered'
        : latest.dispatch?.status === 'blocked' ? 'active'
        : 'queued';
      const updated = await postRuntime(`/api/runtime/delivery-packs/${latest.id}/dispatch`, {
        owner: reviewOwner?.value?.trim() || latest.dispatch?.owner || latest.execution?.owner || latest.review?.owner || 'dispatch-operator',
        status: nextStatus,
        checkpoint: reviewCheckpoint?.value?.trim() || 'queued in local dispatch board',
        notes: deliveryNotes?.value?.trim() || latest.dispatch?.notes || latest.execution?.notes || latest.review?.notes || '',
        targets: latest.targets || latest.dispatch?.targets || latest.execution?.targets || [],
      });
      syncLocalDeliveryFromRuntime(updated.item);
      renderDispatchSummary(updated.summary || {});
      await refreshRuntimeBoard();
      log('Dispatched latest runtime delivery pack', updated.item);
    } catch (error) {
      log('Failed to dispatch runtime delivery pack', { error: error.message });
    }
  });
  document.querySelectorAll('[data-scroll]').forEach((button) => {
    button.addEventListener('click', () => {
      document.querySelectorAll('[data-scroll]').forEach((item) => item.classList.toggle('active', item === button));
      document.getElementById(button.dataset.scroll)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    });
  });

  if ('serviceWorker' in navigator && location.protocol !== 'file:') {
    navigator.serviceWorker.register('./service-worker.js').catch(() => {});
  }

  renderTabs();
  renderTemplateList();
  renderPreview();
  renderProjects();
  renderDeliveries();
  renderExecutionSummary({});
  renderDispatchSummary({});
  renderWorkflowSummary({});
  refreshRuntimeBoard();
  log('SkyeWebCreatorMax full editor/viewer runtime ready');
})();
