#!/usr/bin/env node
import { mkdir, readFile, writeFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { LocalAegisCore } from "../packages/aegis-core/dist/index.js";
import { assertNoKnownSecretLeak } from "../packages/core/dist/index.js";
import { findAdapter } from "../packages/providers/dist/index.js";

const root = new URL("..", import.meta.url).pathname;
const proofDir = join(root, ".proof");
const tmpDir = join(proofDir, "built-smoke");
const vaultPath = join(tmpDir, "vault.json");
const passphrase = "built-proof-passphrase-32-chars";
const secretLiteral = "re_BUILT_SECRET_FOR_SMOKE_ONLY";

await rm(tmpDir, { recursive: true, force: true });
await mkdir(tmpDir, { recursive: true });

const aegis = new LocalAegisCore({ vaultPath, passphrase, projectId: "proof_project" });
const manifest = await aegis.importEnvText(`RESEND_API_KEY=${secretLiteral}\nRESEND_FROM=Proof <proof@example.com>`);
assertNoKnownSecretLeak(manifest, { RESEND_API_KEY: secretLiteral });

const rawVault = await readFile(vaultPath, "utf8");
if (rawVault.includes(secretLiteral)) throw new Error("FAIL: built AegisCore vault leaked raw secret literal.");

const resend = findAdapter("email.send");
const inspect = findAdapter("db.inspect_schema");
const storage = findAdapter("storage.upload");
if (!resend || !inspect || !storage) throw new Error("FAIL: expected adapters were not registered.");

const missingResult = await resend.execute({ to: "proof@example.com", subject: "Proof", body: "Proof" }, { provider: "resend", secrets: {} });
if (missingResult.ok || missingResult.error?.code !== "missing_secrets") throw new Error("FAIL: missing secret guard did not fire.");

const result = {
  ok: true,
  checkedAt: new Date().toISOString(),
  checks: [
    "built packages import successfully from dist",
    "AegisCore built package encrypts vault without raw secret leakage",
    "safe manifest generated by built package omits raw secret literal",
    "provider registry includes email.send, db.inspect_schema, and storage.upload",
    "provider adapters reject missing secrets before live calls"
  ],
  secrets_exposed: false
};
await writeFile(join(proofDir, "built-smoke-result.json"), `${JSON.stringify(result, null, 2)}\n`);
console.log(JSON.stringify(result, null, 2));
