const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const crypto = require('crypto');
const code = fs.readFileSync(require.resolve('../assets/core.js'), 'utf8');
const sandbox = { console, module: { exports: {} }, crypto: { randomUUID: () => crypto.randomUUID(), getRandomValues: (arr) => crypto.webcrypto.getRandomValues(arr) } };
sandbox.globalThis = sandbox;
vm.runInNewContext(code, sandbox, { filename: 'assets/core.js' });
const Core = sandbox.module.exports || sandbox.SignInProCore;
assert.equal(Core.APP_VERSION, '6.4.0-workspace-closure');
assert.equal(Core.WORKSPACE_STATE_PREFIX, 'signinpro_workspace_state_v4');
const state = Core.sanitizeState(Core.DEFAULT_STATE);
let result = Core.createAttendee({ name: ' Ada Lovelace ', nickname: 'Ada', email: 'ADA@example.com', company: 'Analytical Engines', role: 'VIP' }, state.attendees, state.settings);
assert.equal(result.ok, true, 'valid attendee should pass');
assert.match(result.attendee.eventId, /^[23456789ABCDEFGHJKLMNPQRSTUVWXYZ]{4}-[23456789ABCDEFGHJKLMNPQRSTUVWXYZ]{4}$/, 'event id format should be readable');
state.attendees.push(result.attendee);
let duplicate = Core.createAttendee({ name: 'Ada Two', email: 'ada@example.com' }, state.attendees, state.settings);
assert.equal(duplicate.ok, false, 'duplicate email should be blocked by default');
let bad = Core.createAttendee({ name: '', email: 'not-an-email' }, state.attendees, state.settings);
assert.equal(bad.ok, false, 'invalid attendee should fail');
const backup = Core.buildBackup(state);
const parsed = Core.parseBackup(JSON.stringify(backup));
assert.equal(parsed.ok, true, 'backup should parse');
assert.equal(parsed.state.attendees.length, 1, 'backup attendee count should roundtrip');
console.log('core smoke passed:', Core.APP_VERSION, 'attendees:', parsed.state.attendees.length);
