[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/ecosystem.html"
  status = 200

[[redirects]]
  from = "/ecosystem"
  to = "/ecosystem.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/ecosystem.html"
  status = 200
