apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: citadeldb-ha
  namespace: citadeldb
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:18

  primaryUpdateStrategy: unsupervised

  storage:
    size: 20Gi

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: citadel
      owner: citadel_admin
      secret:
        name: citadeldb-superuser

  superuserSecret:
    name: citadeldb-superuser

  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: "512MB"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: "all"
    pg_hba:
      - host all all 10.0.0.0/8 scram-sha-256

  backup:
    retentionPolicy: "14d"
    barmanObjectStore:
      destinationPath: "s3://CHANGE_ME_BUCKET/citadeldb"
      endpointURL: "https://CHANGE_ME_S3_ENDPOINT"
      s3Credentials:
        accessKeyId:
          name: citadeldb-objectstore
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: citadeldb-objectstore
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
