apiVersion: v1
kind: Secret
metadata:
  name: citadeldb-superuser
  namespace: citadeldb
type: kubernetes.io/basic-auth
stringData:
  username: citadel_admin
  password: CHANGE_THIS_SUPERUSER_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: citadeldb-objectstore
  namespace: citadeldb
type: Opaque
stringData:
  ACCESS_KEY_ID: CHANGE_ME
  SECRET_ACCESS_KEY: CHANGE_ME
