window.FOUNDER_SONG_VAULT = {
  "version": 1,
  "generatedAt": "2026-05-26T02:25:59.391Z",
  "generatedBy": "tools/founder-command/build-founder-song-vault.mjs",
  "vaultRoot": "metraiyux_0s_site/founder-command/song-vault",
  "browserRoot": "/founder-command/song-vault/",
  "sourceRoots": [
    "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio",
    ".1/gray-skyes-agent-universe/media/audio",
    ".1/next-artist-universe-intake/assets-drop/audio",
    "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin"
  ],
  "count": 34,
  "totalBytes": 142152449,
  "songs": [
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-always-try-to-breathe",
      "slug": "audio-gray-skyes-catalog-always-try-to-breathe",
      "title": "Always Try To Breathe",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "always-try-to-breathe.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 1643459,
      "sha256": "198a23db02e7dc589cfe4744c9ef817d866a0d295a829ccfe49c42c3b125fc50",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/always-try-to-breathe.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/always-try-to-breathe.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/always-try-to-breathe.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/always-try-to-breathe.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/Gray Skyes - Always Try To Breathe (mastered) (1).mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/always-try-to-breathe.mp3"
    },
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-blades",
      "slug": "audio-gray-skyes-catalog-blades",
      "title": "Blades",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "blades.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 4877696,
      "sha256": "f57d7a9d411dd238fdb5b813be65ea2d868ec17954f561297349533408383697",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/blades.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/blades.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/blades.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/blades.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/BLADES GRAY MIX 1 SCOOTER .mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/blades.mp3"
    },
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-cupid",
      "slug": "audio-gray-skyes-catalog-cupid",
      "title": "Cupid",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "cupid.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 7601408,
      "sha256": "7224b1348f647e31908afc84f0d1ff1b251401eeb16ee66a15d38ec9ce51e38d",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/cupid.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/cupid.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/cupid.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/cupid.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/CUPID MIX 1 SCOOTER  (4).mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/cupid.mp3"
    },
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-cvs-at-12",
      "slug": "audio-gray-skyes-catalog-cvs-at-12",
      "title": "CVS At 12",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "cvs-at-12.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2242768,
      "sha256": "c0f09182f2730a99a1fec74d117116a292c245ba5f5478a4f93f2e5b3c2a9407",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/cvs-at-12.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/cvs-at-12.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/cvs-at-12.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/cvs-at-12.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/CVS@12.mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/cvs-at-12.mp3"
    },
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-fatallity-french-mix",
      "slug": "audio-gray-skyes-catalog-fatallity-french-mix",
      "title": "Fatallity French Mix",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "fatallity-french-mix.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 6423860,
      "sha256": "a9f8185e262576d7ca009af41c08bef63d0e505dd71e1a5a768c967c26cf3313",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/fatallity-french-mix.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/fatallity-french-mix.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/fatallity-french-mix.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/fatallity-french-mix.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/FATALLITY cant spell GRAY FRENCH MIX 1 SCOOTER  (1).mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/fatallity-french-mix.mp3"
    },
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-fuck-yo-society",
      "slug": "audio-gray-skyes-catalog-fuck-yo-society",
      "title": "Fuck Yo Society",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "fuck-yo-society.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2714528,
      "sha256": "d9506b9e2cc69f2dc3858f38708b91792beb37d16fb2c3a20dc4db5fa64ec16d",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/fuck-yo-society.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/fuck-yo-society.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/fuck-yo-society.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/fuck-yo-society.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/FUCK YO SOCIETY MIX 1 SCOOTER  (7).mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/fuck-yo-society.mp3"
    },
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-gray-gang",
      "slug": "audio-gray-skyes-catalog-gray-gang",
      "title": "Gray Gang",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "gray-gang.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 1489187,
      "sha256": "33519b80fa5a5e9c1d8fc26574b680276a294d67b3ad1d68be29ec4bdace0a0c",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/gray-gang.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/gray-gang.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/gray-gang.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/gray-gang.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/Gray Gang.mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/gray-gang.mp3"
    },
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-hands-up",
      "slug": "audio-gray-skyes-catalog-hands-up",
      "title": "Hands Up",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "hands-up.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 4682048,
      "sha256": "3bae35d169877b2aca7c3ee280447124395be9123117f8fd5c5783b917dc347b",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/hands-up.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/hands-up.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/hands-up.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/hands-up.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/HANDS UP MIX 1 SCOOTER  (3).mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/HANDS UP MIX 1 SCOOTER .mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/hands-up.mp3"
    },
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-its-not-over",
      "slug": "audio-gray-skyes-catalog-its-not-over",
      "title": "It's Not Over",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "its-not-over.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2401846,
      "sha256": "e35041221598986497e1c8442268cf33282c2ea98dc0f49b14d729fec74f6a8a",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/its-not-over.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/its-not-over.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/its-not-over.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/its-not-over.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/Gray Skyes - Its Not Over (prod_wetgropes) (mastered) (1).mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/its-not-over.mp3"
    },
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-naruto",
      "slug": "audio-gray-skyes-catalog-naruto",
      "title": "Naruto",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "naruto.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 1967750,
      "sha256": "c288b8260bd73e8d9e62d2911ceb83e78f5bd4b41b7aeced69b0c3f8a1b5724a",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/naruto.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/naruto.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/naruto.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/naruto.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/Naruto (1).mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/naruto.mp3"
    },
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-summer-time",
      "slug": "audio-gray-skyes-catalog-summer-time",
      "title": "Summer Time",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "summer-time.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 6384128,
      "sha256": "0caca6184b9632d5f7c7a8b8cca4e3be2a12e26e53c4e426171c2d18086e70e7",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/summer-time.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/summer-time.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/summer-time.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/summer-time.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/SUMMER TIME mix 1 SCOOTER .mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/summer-time.mp3"
    },
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-take-off-ya-clothes",
      "slug": "audio-gray-skyes-catalog-take-off-ya-clothes",
      "title": "Take Off Ya Clothes",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "take-off-ya-clothes.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 3796740,
      "sha256": "5570b848d69304d00291a148fc4017e3cdac9ba39466d0731951f2fd229f7f8a",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/take-off-ya-clothes.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/take-off-ya-clothes.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/take-off-ya-clothes.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/take-off-ya-clothes.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/Take Off Ya Clothes (2).mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/take-off-ya-clothes.mp3"
    },
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-tidal-waves",
      "slug": "audio-gray-skyes-catalog-tidal-waves",
      "title": "Tidal Waves",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "tidal-waves.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 6182528,
      "sha256": "3c953c712081eac6c2979ddc534d686ae5f77202f003cd0dccfad76d2b673429",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/tidal-waves.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/tidal-waves.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/tidal-waves.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/tidal-waves.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/TIDAL WAVES mix 1 SCOOTER  (4).mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/tidal-waves.mp3"
    },
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-youre-never-alone-mix-3",
      "slug": "audio-gray-skyes-catalog-youre-never-alone-mix-3",
      "title": "You're Never Alone Mix 3",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "youre-never-alone-mix-3.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 8785088,
      "sha256": "5723de28755e5cdb59fdcaf6010f32d5350bfaa2743e19340a8bde2cc385c8e1",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/youre-never-alone-mix-3.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/youre-never-alone-mix-3.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/youre-never-alone-mix-3.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/youre-never-alone-mix-3.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/you're never alone MIX 3 SCOOTER  (3).mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/youre-never-alone-mix-3.mp3"
    },
    {
      "id": "gray-skyes-catalog-audio-gray-skyes-catalog-youre-never-alone-mix-4",
      "slug": "audio-gray-skyes-catalog-youre-never-alone-mix-4",
      "title": "You're Never Alone Mix 4",
      "collection": "gray-skyes-catalog",
      "collectionLabel": "Gray Skyes Catalog",
      "fileName": "youre-never-alone-mix-4.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 8771648,
      "sha256": "eec8db3dbab8c34f2a7c9b66af9366382989a80a528e26be6d2ee1918e1e891d",
      "href": "/founder-command/song-vault/audio/gray-skyes-catalog/youre-never-alone-mix-4.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/gray-skyes-catalog/youre-never-alone-mix-4.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/artist-storefronts/gray-skyes/media/audio/youre-never-alone-mix-4.mp3",
      "duplicateSourcePaths": [
        ".1/gray-skyes-agent-universe/media/audio/youre-never-alone-mix-4.mp3",
        ".1/next-artist-universe-intake/assets-drop/audio/you're never alone MIX 4 SCOOTER  (2).mp3"
      ],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/gray-skyes-catalog/youre-never-alone-mix-4.mp3"
    },
    {
      "id": "original-masters-audio-original-masters-im-the-man",
      "slug": "audio-original-masters-im-the-man",
      "title": "I'm The Man",
      "collection": "original-masters",
      "collectionLabel": "Original Masters",
      "fileName": "im-the-man.wav",
      "extension": "wav",
      "mime": "audio/wav",
      "bytes": 26979294,
      "sha256": "8482be6423e2f35e8511b10360dbbe20bf6cf05ef5856dd9bc890ad907bda896",
      "href": "/founder-command/song-vault/audio/original-masters/im-the-man.wav",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/original-masters/im-the-man.wav",
      "sourcePath": ".1/gray-skyes-agent-universe/media/audio/im-the-man.wav",
      "duplicateSourcePaths": [
        ".1/next-artist-universe-intake/assets-drop/audio/Im The Man (original) (2) (3).wav"
      ],
      "deployParts": [
        {
          "index": 1,
          "bytes": 12582912,
          "sha256": "b8af0ace2ff55035850bcdb50e53140300afc9a806daed17d6d0d9412bcf5868",
          "href": "/founder-command/song-vault/parts/audio/original-masters/im-the-man.wav/part-01.bin",
          "vaultPath": "metraiyux_0s_site/founder-command/song-vault/parts/audio/original-masters/im-the-man.wav/part-01.bin"
        },
        {
          "index": 2,
          "bytes": 12582912,
          "sha256": "5ea65bec09bcc6fc0999d2ef147a6134d4ab3ddbe434c35bec612f4d95d58fb1",
          "href": "/founder-command/song-vault/parts/audio/original-masters/im-the-man.wav/part-02.bin",
          "vaultPath": "metraiyux_0s_site/founder-command/song-vault/parts/audio/original-masters/im-the-man.wav/part-02.bin"
        },
        {
          "index": 3,
          "bytes": 1813470,
          "sha256": "5c3ecefcfce7c26328ac9caef231af376dda943e2de1f2b3d317a047a5c7e1d2",
          "href": "/founder-command/song-vault/parts/audio/original-masters/im-the-man.wav/part-03.bin",
          "vaultPath": "metraiyux_0s_site/founder-command/song-vault/parts/audio/original-masters/im-the-man.wav/part-03.bin"
        }
      ],
      "deployHref": ""
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-everything-movie-everything-movie-act-i-birth-of-static-everything-movie-act-i-birth-of-static",
      "slug": "audio-song-creation-bin-everything-movie-everything-movie-act-i-birth-of-static-everything-movie-act-i-birth-of-static",
      "title": "Everything Movie Act I Birth Of Static",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "everything-movie-act-i-birth-of-static.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2880619,
      "sha256": "b8e3c49e8b2c5ac882e8407540eff6a81dd363ff88cc3486f94299b8d7de3232",
      "href": "/founder-command/song-vault/audio/song-creation-bin/everything-movie/everything-movie-act-i-birth-of-static/everything-movie-act-i-birth-of-static.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/everything-movie/everything-movie-act-i-birth-of-static/everything-movie-act-i-birth-of-static.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/everything-movie/everything-movie-act-i-birth-of-static/everything-movie-act-i-birth-of-static.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/everything-movie/everything-movie-act-i-birth-of-static/everything-movie-act-i-birth-of-static.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-everything-movie-everything-movie-act-ii-gate-argument-everything-movie-act-ii-gate-argument",
      "slug": "audio-song-creation-bin-everything-movie-everything-movie-act-ii-gate-argument-everything-movie-act-ii-gate-argument",
      "title": "Everything Movie Act II Gate Argument",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "everything-movie-act-ii-gate-argument.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2881455,
      "sha256": "1ec031821880a7e0c94dea6c6f8707433e344ff368319ae629589d9ceaf2fa9f",
      "href": "/founder-command/song-vault/audio/song-creation-bin/everything-movie/everything-movie-act-ii-gate-argument/everything-movie-act-ii-gate-argument.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/everything-movie/everything-movie-act-ii-gate-argument/everything-movie-act-ii-gate-argument.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/everything-movie/everything-movie-act-ii-gate-argument/everything-movie-act-ii-gate-argument.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/everything-movie/everything-movie-act-ii-gate-argument/everything-movie-act-ii-gate-argument.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-everything-movie-everything-movie-act-iii-betrayal-parade-everything-movie-act-iii-betrayal-parade",
      "slug": "audio-song-creation-bin-everything-movie-everything-movie-act-iii-betrayal-parade-everything-movie-act-iii-betrayal-parade",
      "title": "Everything Movie Act III Betrayal Parade",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "everything-movie-act-iii-betrayal-parade.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2880619,
      "sha256": "63b0998e3457b97131dccb052a722b058086c791c38764172c741c1d29c9b062",
      "href": "/founder-command/song-vault/audio/song-creation-bin/everything-movie/everything-movie-act-iii-betrayal-parade/everything-movie-act-iii-betrayal-parade.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/everything-movie/everything-movie-act-iii-betrayal-parade/everything-movie-act-iii-betrayal-parade.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/everything-movie/everything-movie-act-iii-betrayal-parade/everything-movie-act-iii-betrayal-parade.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/everything-movie/everything-movie-act-iii-betrayal-parade/everything-movie-act-iii-betrayal-parade.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-everything-movie-everything-movie-act-iv-founder-walkout-everything-movie-act-iv-founder-walkout",
      "slug": "audio-song-creation-bin-everything-movie-everything-movie-act-iv-founder-walkout-everything-movie-act-iv-founder-walkout",
      "title": "Everything Movie Act IV Founder Walkout",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "everything-movie-act-iv-founder-walkout.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2881455,
      "sha256": "e55b6199e09ccac8319fedd5d482f34050d1dac8f38075b1ed2b75c386e7cfaf",
      "href": "/founder-command/song-vault/audio/song-creation-bin/everything-movie/everything-movie-act-iv-founder-walkout/everything-movie-act-iv-founder-walkout.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/everything-movie/everything-movie-act-iv-founder-walkout/everything-movie-act-iv-founder-walkout.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/everything-movie/everything-movie-act-iv-founder-walkout/everything-movie-act-iv-founder-walkout.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/everything-movie/everything-movie-act-iv-founder-walkout/everything-movie-act-iv-founder-walkout.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-singles-glass-at-the-line-glass-at-the-line",
      "slug": "audio-song-creation-bin-singles-glass-at-the-line-glass-at-the-line",
      "title": "Glass At The Line",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "glass-at-the-line.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 1692288,
      "sha256": "65fa142a1724b2a47bd00656115cae3030f277cc4127e6b55ad74f3f02b044b3",
      "href": "/founder-command/song-vault/audio/song-creation-bin/singles/glass-at-the-line/glass-at-the-line.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/singles/glass-at-the-line/glass-at-the-line.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/singles/glass-at-the-line/glass-at-the-line.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/singles/glass-at-the-line/glass-at-the-line.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-vox-gray-modes-midnight-r-and-b-mode-midnight-r-and-b-mode",
      "slug": "audio-song-creation-bin-vox-gray-modes-midnight-r-and-b-mode-midnight-r-and-b-mode",
      "title": "Midnight R And B Mode",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "midnight-r-and-b-mode.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2560462,
      "sha256": "9a9b2b28e286a4314cb4d24b61b079f89a01f8caeeaa8d7c9c201125996d167f",
      "href": "/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/midnight-r-and-b-mode/midnight-r-and-b-mode.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/midnight-r-and-b-mode/midnight-r-and-b-mode.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/vox-gray-modes/midnight-r-and-b-mode/midnight-r-and-b-mode.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/midnight-r-and-b-mode/midnight-r-and-b-mode.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-vox-gray-modes-mirror-chat-mirror-chat",
      "slug": "audio-song-creation-bin-vox-gray-modes-mirror-chat-mirror-chat",
      "title": "Mirror Chat",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "mirror-chat.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2400802,
      "sha256": "e985f318d066814100ba744bb373d476dda79b8f12b2f68ae3d4e5c2808c3c26",
      "href": "/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/mirror-chat/mirror-chat.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/mirror-chat/mirror-chat.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/vox-gray-modes/mirror-chat/mirror-chat.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/mirror-chat/mirror-chat.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-singles-neon-glass-relay-neon-glass-relay",
      "slug": "audio-song-creation-bin-singles-neon-glass-relay-neon-glass-relay",
      "title": "Neon Glass Relay",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "neon-glass-relay.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2082432,
      "sha256": "b1c3e5ba8cbbcfbd3479a5fb205c21381a3f0bec37375a1fc7e06279778add12",
      "href": "/founder-command/song-vault/audio/song-creation-bin/singles/neon-glass-relay/neon-glass-relay.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/singles/neon-glass-relay/neon-glass-relay.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/singles/neon-glass-relay/neon-glass-relay.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/singles/neon-glass-relay/neon-glass-relay.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-singles-owner-mode-owner-mode",
      "slug": "audio-song-creation-bin-singles-owner-mode-owner-mode",
      "title": "Owner Mode",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "owner-mode.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2401010,
      "sha256": "12ab2ae0b12506b111996a722b1f5bdc7a767527538df810ed11b2739347ebac",
      "href": "/founder-command/song-vault/audio/song-creation-bin/singles/owner-mode/owner-mode.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/singles/owner-mode/owner-mode.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/singles/owner-mode/owner-mode.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/singles/owner-mode/owner-mode.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-singles-receipts-in-the-sun-receipts-in-the-sun",
      "slug": "audio-song-creation-bin-singles-receipts-in-the-sun-receipts-in-the-sun",
      "title": "Receipts In The Sun",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "receipts-in-the-sun.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2400802,
      "sha256": "1f3a08f378933116ebdb7b6eaea2878a91139fa81231c84032202e59aad506f2",
      "href": "/founder-command/song-vault/audio/song-creation-bin/singles/receipts-in-the-sun/receipts-in-the-sun.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/singles/receipts-in-the-sun/receipts-in-the-sun.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/singles/receipts-in-the-sun/receipts-in-the-sun.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/singles/receipts-in-the-sun/receipts-in-the-sun.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-vox-gray-modes-redline-heart-redline-heart",
      "slug": "audio-song-creation-bin-vox-gray-modes-redline-heart-redline-heart",
      "title": "Redline Heart",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "redline-heart.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2399966,
      "sha256": "0708038d7531eccbe7dc2324a80c98265db1e67f71aa2b5deb639bc4695c8287",
      "href": "/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/redline-heart/redline-heart.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/redline-heart/redline-heart.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/vox-gray-modes/redline-heart/redline-heart.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/redline-heart/redline-heart.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-singles-skyline-service-skyline-service",
      "slug": "audio-song-creation-bin-singles-skyline-service-skyline-service",
      "title": "Skyline Service",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "skyline-service.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2399966,
      "sha256": "3ad326b881a9ad54b7602ae3e4e9e58e9eb694919bc514a8f00a19d992302c4e",
      "href": "/founder-command/song-vault/audio/song-creation-bin/singles/skyline-service/skyline-service.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/singles/skyline-service/skyline-service.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/singles/skyline-service/skyline-service.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/singles/skyline-service/skyline-service.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-vox-gray-modes-slow-rain-reply-slow-rain-reply",
      "slug": "audio-song-creation-bin-vox-gray-modes-slow-rain-reply-slow-rain-reply",
      "title": "Slow Rain Reply",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "slow-rain-reply.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2881455,
      "sha256": "dfca291cd55682e7403a9adbd41e3e9ebd1c8ba71e5a710a9b716c1a4ce08fc0",
      "href": "/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/slow-rain-reply/slow-rain-reply.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/slow-rain-reply/slow-rain-reply.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/vox-gray-modes/slow-rain-reply/slow-rain-reply.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/slow-rain-reply/slow-rain-reply.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-vox-gray-modes-soft-ghost-protocol-soft-ghost-protocol",
      "slug": "audio-song-creation-bin-vox-gray-modes-soft-ghost-protocol-soft-ghost-protocol",
      "title": "Soft Ghost Protocol",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "soft-ghost-protocol.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2399966,
      "sha256": "55bcd3ac21494ec74dc884abb593545804aa41b7337d0967a16ea26c15db21bc",
      "href": "/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/soft-ghost-protocol/soft-ghost-protocol.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/soft-ghost-protocol/soft-ghost-protocol.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/vox-gray-modes/soft-ghost-protocol/soft-ghost-protocol.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/soft-ghost-protocol/soft-ghost-protocol.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-vox-gray-modes-stay-through-static-stay-through-static",
      "slug": "audio-song-creation-bin-vox-gray-modes-stay-through-static-stay-through-static",
      "title": "Stay Through Static",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "stay-through-static.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2880619,
      "sha256": "965142bdf1b6e987cf0c67200f8f3ecb992a1cdabed1c827db6b66a62a720c7f",
      "href": "/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/stay-through-static/stay-through-static.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/stay-through-static/stay-through-static.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/vox-gray-modes/stay-through-static/stay-through-static.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/vox-gray-modes/stay-through-static/stay-through-static.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-singles-storefront-weather-storefront-weather",
      "slug": "audio-song-creation-bin-singles-storefront-weather-storefront-weather",
      "title": "Storefront Weather",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "storefront-weather.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2401010,
      "sha256": "997d5487f8fc4377e5fdab8207c69a815d837324472ea7a4c348fb956537989c",
      "href": "/founder-command/song-vault/audio/song-creation-bin/singles/storefront-weather/storefront-weather.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/singles/storefront-weather/storefront-weather.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/singles/storefront-weather/storefront-weather.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/singles/storefront-weather/storefront-weather.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-singles-velvet-ledger-velvet-ledger",
      "slug": "audio-song-creation-bin-singles-velvet-ledger-velvet-ledger",
      "title": "Velvet Ledger",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "velvet-ledger.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 2880827,
      "sha256": "3e46312cfc8a6988ef77c2ec7cdc7b2a30f2b7c0b4ade175d100b23062ddb0dd",
      "href": "/founder-command/song-vault/audio/song-creation-bin/singles/velvet-ledger/velvet-ledger.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/singles/velvet-ledger/velvet-ledger.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/singles/velvet-ledger/velvet-ledger.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/singles/velvet-ledger/velvet-ledger.mp3"
    },
    {
      "id": "song-creation-bin-audio-song-creation-bin-reflection-wooooah-factor-wooooah-factor",
      "slug": "audio-song-creation-bin-reflection-wooooah-factor-wooooah-factor",
      "title": "Wooooah Factor",
      "collection": "song-creation-bin",
      "collectionLabel": "Song Creation Bin",
      "fileName": "wooooah-factor.mp3",
      "extension": "mp3",
      "mime": "audio/mpeg",
      "bytes": 1902720,
      "sha256": "f7e6c18d8e646fa2d0d8f22b09148f053815445d24e7240087fd3a93f95cbc0a",
      "href": "/founder-command/song-vault/audio/song-creation-bin/reflection/wooooah-factor/wooooah-factor.mp3",
      "vaultPath": "metraiyux_0s_site/founder-command/song-vault/audio/song-creation-bin/reflection/wooooah-factor/wooooah-factor.mp3",
      "sourcePath": "metraiyux_0s_site/SkyeMusicNexus/song-creation-bin/reflection/wooooah-factor/wooooah-factor.mp3",
      "duplicateSourcePaths": [],
      "deployParts": [],
      "deployHref": "/founder-command/song-vault/audio/song-creation-bin/reflection/wooooah-factor/wooooah-factor.mp3"
    }
  ]
};
