[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "https://kaixugateway13.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/launch"
  to = "/app.html"
  status = 200
