const DEFAULT_REPO_TRIAL_DAYS = 7;
export const REPO_STRIPE_CATALOG_SOURCE = "metraiyux_0s_site/brain/sales-offer-registry.json";

const RAW_REPO_STRIPE_PRODUCTS = [
  ["skygate-lane-maintenance-monthly","SkyeGate FS27 Lane Maintenance","$249/month per lane",24900,"usd","recurring","skygatefs27_lane_maintenance_monthly","skygate","SkyePay infrastructure",310,"approved","FS27 approved","SkyeGate FS27","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!/index.html","naomi-sterling-brain","Optional monthly lane maintenance for updates, small tweaks, and support.",["updates","small tweaks","lane support"]],
  ["kaixu-starter-monthly","kAIxU Starter","$249/month",24900,"usd","recurring","kaixu_starter_monthly","kaixu","kAIxU platform",351,"approved","kAIxU approved","skyesol_current_public_site/SkyeSol/skyesol-main/kAIxu","skyesol_current_public_site/SkyeSol/skyesol-main/kAIxu/pricing.html","orion-hayes-brain","Platform access for independent operators needing projects, keys, and usage visibility.",["up to 3 projects","up to 5 keys","1 seat","usage dashboard","key rotation","basic limits"]],
  ["kaixu-team-monthly","kAIxU Team","$799/month",79900,"usd","recurring","kaixu_team_monthly","kaixu","kAIxU platform",352,"approved","kAIxU approved","skyesol_current_public_site/SkyeSol/skyesol-main/kAIxu","skyesol_current_public_site/SkyeSol/skyesol-main/kAIxu/pricing.html","orion-hayes-brain","Platform access for teams shipping products.",["up to 15 projects","up to 50 keys","5 seats","usage alerts","role-based access","project limits"]],
  ["kaixu-scale-monthly","kAIxU Scale","$1,890/month",189000,"usd","recurring","kaixu_scale_monthly","kaixu","kAIxU platform",353,"approved","kAIxU approved","skyesol_current_public_site/SkyeSol/skyesol-main/kAIxu","skyesol_current_public_site/SkyeSol/skyesol-main/kAIxu/pricing.html","orion-hayes-brain","Platform access for multi-client operations.",["up to 60 projects","up to 250 keys","20 seats","audit exports","advanced limits","priority support lane"]],
  ["lane-vault-kaixu-upgrade","kAIxU Powered Lane Upgrade","$7,500 setup per lane",750000,"usd","one_time","lane_vault_kaixu_powered_upgrade_setup","lane_vault","Lane Vault builds",404,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!/index.html","orion-hayes-brain","Add intelligence inside a lane for summaries, next steps, drafts, missing-info checks, and reports.",["summaries","next steps","draft replies","missing-info checks","report drafting"]],
  ["xinth-governance-platform-monthly","Xinth Governance Platform Access","$1,250/month",125000,"usd","recurring","xinth_governance_platform_monthly","lane_vault","Lane Vault builds",405,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!/index.html","naomi-sterling-brain","Recurring platform access for governance, keys, metering, exports, and billing controls.",["master/sub-keys","caps","rate limits","device binding","allowlists","metering","exports","invoice summaries"]],
  ["xinth-governance-onboarding","Xinth Governance and Billing Onboarding","$12,500 onboarding",1250000,"usd","one_time","xinth_governance_billing_onboarding","lane_vault","Lane Vault builds",406,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!/index.html","naomi-sterling-brain","Onboarding for Xinth governance and billing controls.",["key setup","policy setup","metering setup","billing control setup"]],
  ["lane-vault-maintenance-monthly","Lane Vault Maintenance Plan","$249/month per lane",24900,"usd","recurring","lane_vault_maintenance_monthly_per_lane","lane_vault","Lane Vault builds",407,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!/index.html","celeste-monroe-brain","Ongoing care for lane updates, small tweaks, and support.",["lane updates","small tweaks","support"]],
  ["lane-vault-intake-lane-build","Lane Vault - Intake Lane","$9,500 build",950000,"usd","one_time","lane_vault_intake_lane_build","lane_vault","Lane Vault builds",408,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!/index.html","celeste-monroe-brain","Branded lead and intake vault lane build.",["forms","uploads","routing","follow-ups","visibility"]],
  ["lane-vault-front-office-lane-build","Lane Vault - Front Office Lane","$12,500 build",1250000,"usd","one_time","lane_vault_front_office_lane_build","lane_vault","Lane Vault builds",409,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!/index.html","celeste-monroe-brain","Branded front-office command desk for staff workflow.",["call logs","tasks","notes","customer records","status tags","daily workflow"]],
  ["lane-vault-compliance-vault-lane-build","Lane Vault - Compliance Vault Lane","$22,500 build",2250000,"usd","one_time","lane_vault_compliance_vault_lane_build","lane_vault","Lane Vault builds",410,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!/index.html","donovan-pierce-brain","Branded compliance vault for policies, documents, approvals, and proof packs.",["policy storage","document vault","approvals","proof packs","audit readiness"]],
  ["sbcc-starter-monthly","Skye Business Command Center - Starter Hosting and Support","$99/month",9900,"usd","recurring","sbcc_starter_hosting_support_monthly","business_command_center","Business Command Center",711,"approved","SBCC approved","skye-business-command-center","skye-business-command-center/docs/SALES_OFFER_PACK.md","celeste-monroe-brain","Monthly hosting and support for a starter small-business operations portal.",["hosting","monthly support","backup checks"]],
  ["sbcc-starter-setup","Skye Business Command Center - Starter Ops Portal Setup","$497 setup",49700,"usd","one_time","sbcc_starter_ops_portal_setup","business_command_center","Business Command Center",712,"approved","SBCC approved","skye-business-command-center","skye-business-command-center/docs/SALES_OFFER_PACK.md","celeste-monroe-brain","Setup for starter branded operations portal.",["support inbox","basic intake forms","basic CRM setup","branded dashboard","deployment"]],
  ["sbcc-business-monthly","Skye Business Command Center - Business Monthly Support","$199/month",19900,"usd","recurring","sbcc_business_monthly_support","business_command_center","Business Command Center",713,"approved","SBCC approved","skye-business-command-center","skye-business-command-center/docs/SALES_OFFER_PACK.md","celeste-monroe-brain","Monthly support for the Business Command Center.",["support","email routing","backup checks","training support"]],
  ["sbcc-business-setup","Skye Business Command Center - Business Setup","$997 setup",99700,"usd","one_time","sbcc_business_command_center_setup","business_command_center","Business Command Center",714,"approved","SBCC approved","skye-business-command-center","skye-business-command-center/docs/SALES_OFFER_PACK.md","celeste-monroe-brain","Setup for CRM, support inbox, estimates/invoices, forms, branding, staff setup, and training.",["CRM pipeline","support inbox","estimates/invoices","intake forms","branded dashboard","staff setup","training"]],
  ["sbcc-dedicated-instance-monthly-floor","Skye Business Command Center - Dedicated Instance Monthly Floor","starts at $750/month",75000,"usd","recurring_floor","sbcc_dedicated_instance_monthly_floor","business_command_center","Business Command Center",715,"approved_floor","Starts at","skye-business-command-center","skye-business-command-center/docs/COSTS.md","naomi-sterling-brain","Dedicated instance support floor for clients needing stronger isolation.",["dedicated VPS support","priority maintenance","backup/restore test"]],
  ["sol-staffing-operator-command-monthly","SOL Staffing OS - Operator Command","$1,500/month",150000,"usd","recurring","sol_staffing_operator_command_monthly","sol_staffing","SOL Staffing OS",776,"approved","SOL approved","marketing/sol-staffing","marketing/sol-staffing/index.html","celeste-monroe-brain","Managed operator command subscription for staffing OS clients.",["managed operating cadence","operator command support","staffing OS guidance"]],
  ["sol-staffing-direct-launch-site","SOL Staffing OS - Direct Launch Site","$2,500 one-time",250000,"usd","one_time","sol_staffing_direct_launch_site","sol_staffing","SOL Staffing OS",777,"approved","SOL approved","marketing/sol-staffing","marketing/sol-staffing/index.html","celeste-monroe-brain","Direct launch-site package for staffing brands.",["launch website","staffing positioning","public offer surface"]],
  ["sol-staffing-direct-live-os","SOL Staffing OS - Direct Live Staffing OS","$7,500 one-time",750000,"usd","one_time","sol_staffing_direct_live_staffing_os","sol_staffing","SOL Staffing OS",778,"approved","SOL approved","marketing/sol-staffing","marketing/sol-staffing/index.html","celeste-monroe-brain","Direct live staffing operating system package.",["staffing OS","operating surfaces","sales and operations support"]],
  ["sol-staffing-white-label-live-os","SOL Staffing OS - White-Label Live OS Package","$8,500 setup",850000,"usd","one_time","sol_staffing_white_label_live_os_package_setup","sol_staffing","SOL Staffing OS",779,"approved","SOL approved","marketing/sol-staffing","marketing/sol-staffing/white-label.html","celeste-monroe-brain","White-label live staffing OS setup for operator partners.",["white-label staffing OS","operator partner setup","deployment package"]],
  ["lane-vault-delivery-lane-build","Lane Vault - Delivery Lane","$18,500 build",1850000,"usd","one_time","lane_vault_delivery_lane_build","lane_vault","Lane Vault builds",420,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","STRIPE_PRODUCT_PRICE_CATALOG.md","celeste-monroe-brain","Create full one-time build products; use quotes for financing examples.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["lane-vault-client-portal-lane-build","Lane Vault - Client Portal Lane","$14,500 build",1450000,"usd","one_time","lane_vault_client_portal_lane_build","lane_vault","Lane Vault builds",421,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","STRIPE_PRODUCT_PRICE_CATALOG.md","celeste-monroe-brain","Create full one-time build products; use quotes for financing examples.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["lane-vault-contractor-lane-build","Lane Vault - Contractor Lane","$16,500 build",1650000,"usd","one_time","lane_vault_contractor_lane_build","lane_vault","Lane Vault builds",422,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","STRIPE_PRODUCT_PRICE_CATALOG.md","celeste-monroe-brain","Create full one-time build products; use quotes for financing examples.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["lane-vault-reporting-lane-build","Lane Vault - Reporting Lane","$13,500 build",1350000,"usd","one_time","lane_vault_reporting_lane_build","lane_vault","Lane Vault builds",423,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","STRIPE_PRODUCT_PRICE_CATALOG.md","celeste-monroe-brain","Create full one-time build products; use quotes for financing examples.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["lane-vault-scheduling-lane-build","Lane Vault - Scheduling Lane","$11,500 build",1150000,"usd","one_time","lane_vault_scheduling_lane_build","lane_vault","Lane Vault builds",424,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","STRIPE_PRODUCT_PRICE_CATALOG.md","celeste-monroe-brain","Create full one-time build products; use quotes for financing examples.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["lane-vault-inventory-lane-build","Lane Vault - Inventory Lane","$17,500 build",1750000,"usd","one_time","lane_vault_inventory_lane_build","lane_vault","Lane Vault builds",425,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","STRIPE_PRODUCT_PRICE_CATALOG.md","celeste-monroe-brain","Create full one-time build products; use quotes for financing examples.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["lane-vault-billing-lane-build","Lane Vault - Billing Lane","$19,500 build",1950000,"usd","one_time","lane_vault_billing_lane_build","lane_vault","Lane Vault builds",426,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","STRIPE_PRODUCT_PRICE_CATALOG.md","celeste-monroe-brain","Create full one-time build products; use quotes for financing examples.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["lane-vault-hr-onboarding-lane-build","Lane Vault - HR Onboarding Lane","$16,500 build",1650000,"usd","one_time","lane_vault_hr_onboarding_lane_build","lane_vault","Lane Vault builds",427,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","STRIPE_PRODUCT_PRICE_CATALOG.md","celeste-monroe-brain","Create full one-time build products; use quotes for financing examples.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["lane-vault-support-lane-build","Lane Vault - Support Lane","$15,500 build",1550000,"usd","one_time","lane_vault_support_lane_build","lane_vault","Lane Vault builds",428,"approved","Lane build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/Lane-Vault!","STRIPE_PRODUCT_PRICE_CATALOG.md","celeste-monroe-brain","Create full one-time build products; use quotes for financing examples.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["skyecorp-phase1-opsdesk-agent-suite-build","kAIxU OpsDesk Agent Suite","$28,500 build",2850000,"usd","one_time","skyecorp_phase1_opsdesk_agent_suite_build","skyecorp","SkyeCorp systems",529,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/Phase1","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products when actively selling this catalog.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["skyecorp-phase1-sales-followup-agent-build","kAIxU Sales Follow-Up Agent","$19,500 build",1950000,"usd","one_time","skyecorp_phase1_sales_followup_agent_build","skyecorp","SkyeCorp systems",530,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/Phase1","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products when actively selling this catalog.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["skyecorp-phase1-financeguard-agent-build","kAIxU FinanceGuard Agent","$22,500 build",2250000,"usd","one_time","skyecorp_phase1_financeguard_agent_build","skyecorp","SkyeCorp systems",531,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/Phase1","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products when actively selling this catalog.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["skyecorp-phase1-supportcopilot-agent-build","kAIxU SupportCopilot Agent","$24,500 build",2450000,"usd","one_time","skyecorp_phase1_supportcopilot_agent_build","skyecorp","SkyeCorp systems",532,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/Phase1","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products when actively selling this catalog.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["skyecorp-phase1-hiring-onboarding-agent-build","kAIxU Hiring and Onboarding Agent","$18,500 build",1850000,"usd","one_time","skyecorp_phase1_hiring_onboarding_agent_build","skyecorp","SkyeCorp systems",533,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/Phase1","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products when actively selling this catalog.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["skyecorp-phase1-compliance-audit-agent-build","kAIxU Compliance and Audit Agent","$32,500 build",3250000,"usd","one_time","skyecorp_phase1_compliance_audit_agent_build","skyecorp","SkyeCorp systems",534,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/Phase1","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products when actively selling this catalog.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-01-smb-company-os-build","0megaPhase Pack 01 - SMB Company OS","$35,000 build",3500000,"usd","one_time","omegaphase_pack_01_smb_company_os_build","skyecorp","SkyeCorp systems",535,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-02-field-service-ops-build","0megaPhase Pack 02 - Field Service Ops","$55,000 build",5500000,"usd","one_time","omegaphase_pack_02_field_service_ops_build","skyecorp","SkyeCorp systems",536,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-03-property-mgmt-ops-build","0megaPhase Pack 03 - Property Management Maintenance Ops","$60,000 build",6000000,"usd","one_time","omegaphase_pack_03_property_mgmt_ops_build","skyecorp","SkyeCorp systems",537,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-04-contact-center-support-ops-build","0megaPhase Pack 04 - Contact Center Support Ops","$40,000 build",4000000,"usd","one_time","omegaphase_pack_04_contact_center_support_ops_build","skyecorp","SkyeCorp systems",538,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-05-compliance-proof-trust-center-build","0megaPhase Pack 05 - Compliance Proof Trust Center","$65,000 build",6500000,"usd","one_time","omegaphase_pack_05_compliance_proof_trust_center_build","skyecorp","SkyeCorp systems",539,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-06-identity-access-governance-build","0megaPhase Pack 06 - Identity Access Governance","$45,000 build",4500000,"usd","one_time","omegaphase_pack_06_identity_access_governance_build","skyecorp","SkyeCorp systems",540,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-07-creator-agency-ops-build","0megaPhase Pack 07 - Creator Agency Ops","$50,000 build",5000000,"usd","one_time","omegaphase_pack_07_creator_agency_ops_build","skyecorp","SkyeCorp systems",541,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-08-public-sector-requests-portal-build","0megaPhase Pack 08 - Public Sector Requests Portal","$70,000 build",7000000,"usd","one_time","omegaphase_pack_08_public_sector_requests_portal_build","skyecorp","SkyeCorp systems",542,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-09-healthcare-adjacent-ops-build","0megaPhase Pack 09 - Healthcare Adjacent Ops","$58,000 build",5800000,"usd","one_time","omegaphase_pack_09_healthcare_adjacent_ops_build","skyecorp","SkyeCorp systems",543,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-10-legal-intake-case-flow-build","0megaPhase Pack 10 - Legal Intake Case Flow","$75,000 build",7500000,"usd","one_time","omegaphase_pack_10_legal_intake_case_flow_build","skyecorp","SkyeCorp systems",544,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-11-insurance-adjuster-claims-ops-build","0megaPhase Pack 11 - Insurance Adjuster Claims Ops","$80,000 build",8000000,"usd","one_time","omegaphase_pack_11_insurance_adjuster_claims_ops_build","skyecorp","SkyeCorp systems",545,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-12-franchise-multi-location-os-build","0megaPhase Pack 12 - Franchise Multi-Location OS","$120,000 build",12000000,"usd","one_time","omegaphase_pack_12_franchise_multi_location_os_build","skyecorp","SkyeCorp systems",546,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-13-logistics-fleet-dispatch-ops-build","0megaPhase Pack 13 - Logistics Fleet Dispatch Ops","$95,000 build",9500000,"usd","one_time","omegaphase_pack_13_logistics_fleet_dispatch_ops_build","skyecorp","SkyeCorp systems",547,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-14-retail-dtc-brand-ops-build","0megaPhase Pack 14 - Retail DTC Brand Operations","$85,000 build",8500000,"usd","one_time","omegaphase_pack_14_retail_dtc_brand_ops_build","skyecorp","SkyeCorp systems",548,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]],
  ["omegaphase-pack-15-task-agents-business-apps-build","0megaPhase Pack 15 - Task Agents Inside Business Apps","$35,000 build",3500000,"usd","one_time","omegaphase_pack_15_task_agents_business_apps_build","skyecorp","SkyeCorp systems",549,"approved","SkyeCorp build","skyesol_current_public_site/SkyeSol/skyesol-main/Services/SkyeCorp/0megaPhase","STRIPE_PRODUCT_PRICE_CATALOG.md","orion-hayes-brain","Create one-time build products for packaged operating-system deals.",["owner-approved scope closeout","Stripe-backed checkout","FS27 order ledger"]]
];

function slugPlanName(id) {
  return String(id || "")
    .replace(/-(monthly|setup|build|one-time|floor)$/g, "")
    .slice(0, 100);
}

function isRecurring(priceType) {
  return String(priceType || "").startsWith("recurring");
}

function normalizeRepoProduct(row) {
  const [
    id,
    productName,
    priceLabel,
    amountCents,
    currency,
    priceType,
    lookupKey,
    family,
    storeCategory,
    storeRank,
    status,
    badge,
    sourceFolder,
    sourceFile,
    brainOwner,
    salesUse,
    includes
  ] = row;
  const recurring = isRecurring(priceType);

  return {
    id,
    plan_name: slugPlanName(id),
    title: productName,
    family,
    description: salesUse || "Approved checkout product from the repo SkyePay settlement catalog.",
    currency,
    mode: recurring ? "subscription" : "payment",
    lookup_keys: [lookupKey],
    line_items: [
      {
        id: recurring ? "monthly" : "one-time",
        name: productName,
        amount_cents: amountCents,
        type: recurring ? "recurring" : "one_time",
        ...(recurring ? { interval: "month" } : {}),
        lookup_key: lookupKey
      }
    ],
    trial_days: recurring ? DEFAULT_REPO_TRIAL_DAYS : 0,
    zero_upfront_trial: recurring,
    setup_handling: recurring ? "deferred_owner_approval" : null,
    store_category: storeCategory,
    store_rank: storeRank,
    badge,
    includes: Array.isArray(includes) ? includes : [],
    owner_approval_required: true,
    activation_path: "paid_pending_owner_approval",
    status,
    price_label: priceLabel,
    catalog_source: REPO_STRIPE_CATALOG_SOURCE,
    source_folder: sourceFolder,
    source_file: sourceFile,
    brain_owner: brainOwner,
    catalog_note: "Generated from the repo-approved Stripe sales registry; metered, variable, quote-only, and do-not-create rows stay out of public checkout."
  };
}

export const SKYPAY_REPO_STRIPE_OFFERS = RAW_REPO_STRIPE_PRODUCTS.map(normalizeRepoProduct);

export const SKYPAY_REPO_STRIPE_OFFER_COUNT = SKYPAY_REPO_STRIPE_OFFERS.length;
