const text = (v = '') => String(v || '').trim();
const num = (v, f = 0) => Number.isFinite(Number(v)) ? Math.trunc(Number(v)) : f;
const bool = (v, f = false) => v === undefined || v === null || v === '' ? f : v === true || v === 'true' || v === '1' || v === 1;
const asJson = (v, f) => Array.isArray(v) || (v && typeof v === 'object') ? v : (() => { try { return JSON.parse(v || ''); } catch { return f; } })();
const key = (v = '') => text(v).toLowerCase().replace(/[^a-z0-9._:-]+/g, '_').replace(/^_+|_+$/g, '');
export function normalizeRegisterInput(body = {}, existing = {}) { return { name: text(body.name || existing.name || 'Main Register'), locationId: text(body.locationId || existing.locationId), status: key(body.status || existing.status || 'active') || 'active', cashDrawerCents: Math.max(0, num(body.cashDrawerCents ?? existing.cashDrawerCents, 0)), active: bool(body.active, existing.active ?? true) }; }
export function registerRecord(row) { if (!row) return null; return { id: row.id || '', merchantId: row.merchant_id || row.merchantId || '', name: row.name || '', locationId: row.location_id || row.locationId || '', locationName: row.location_name || row.locationName || '', status: row.status || 'active', cashDrawerCents: Number(row.cash_drawer_cents ?? row.cashDrawerCents ?? 0), active: Boolean(Number(row.active ?? 1)), createdAt: row.created_at || row.createdAt || '', updatedAt: row.updated_at || row.updatedAt || '' }; }
export function normalizeShiftOpenInput(body = {}, register = {}) { return { registerId: text(body.registerId || register.id), staffMemberId: text(body.staffMemberId), openingCashCents: Math.max(0, num(body.openingCashCents, register.cashDrawerCents || 0)), note: text(body.note) }; }
export function normalizeShiftCloseInput(body = {}) { return { closingCashCents: Math.max(0, num(body.closingCashCents, 0)), note: text(body.note) }; }
export function shiftRecord(row) { if (!row) return null; return { id: row.id || '', merchantId: row.merchant_id || row.merchantId || '', registerId: row.register_id || row.registerId || '', registerName: row.register_name || row.registerName || '', staffMemberId: row.staff_member_id || row.staffMemberId || '', staffName: row.staff_name || row.staffName || '', status: row.status || 'open', openingCashCents: Number(row.opening_cash_cents ?? row.openingCashCents ?? 0), closingCashCents: Number(row.closing_cash_cents ?? row.closingCashCents ?? 0), cashExpectedCents: Number(row.cash_expected_cents ?? row.cashExpectedCents ?? 0), cashVarianceCents: Number(row.cash_variance_cents ?? row.cashVarianceCents ?? 0), openedAt: row.opened_at || row.openedAt || row.created_at || '', closedAt: row.closed_at || row.closedAt || '', note: row.note || '' }; }
export function normalizePosCartItem(item = {}) { const quantity = Math.max(1, num(item.quantity, 1)); const unitPriceCents = Math.max(0, num(item.unitPriceCents ?? item.unit_price_cents, 0)); return { productId: text(item.productId || item.product_id), variantId: text(item.variantId || item.variant_id), sku: text(item.sku), title: text(item.title || 'POS Item'), quantity, unitPriceCents, lineTotalCents: quantity * unitPriceCents }; }
export function calculatePosCartTotals(items = [], opts = {}) { const subtotalCents = (Array.isArray(items) ? items : []).reduce((sum, item) => sum + Number(item.lineTotalCents ?? (Number(item.quantity || 0) * Number(item.unitPriceCents || 0))), 0); const discountCents = Math.min(subtotalCents, Math.max(0, num(opts.discountCents, 0))); const taxable = Math.max(0, subtotalCents - discountCents); const taxCents = opts.taxCents !== undefined ? Math.max(0, num(opts.taxCents, 0)) : Math.floor(taxable * Math.max(0, num(opts.taxBps, 0)) / 10000); return { subtotalCents, discountCents, taxCents, totalCents: Math.max(0, taxable + taxCents) }; }
export function normalizePosCartInput(body = {}, existing = {}) { const items = asJson(body.items, body.items || existing.items || []).map(normalizePosCartItem).filter((i) => i.productId || i.sku || i.title); const totals = calculatePosCartTotals(items, body); return { registerId: text(body.registerId || existing.registerId), shiftId: text(body.shiftId || existing.shiftId), customerId: text(body.customerId || existing.customerId), status: key(body.status || existing.status || 'open') || 'open', currency: text(body.currency || existing.currency || 'USD').toUpperCase(), items, tenders: asJson(body.tenders, body.tenders || existing.tenders || []), ...totals }; }
export function normalizeTenderInput(tender = {}) { return { type: key(tender.type || 'cash') || 'cash', amountCents: Math.max(0, num(tender.amountCents ?? tender.amount_cents, 0)), reference: text(tender.reference || tender.providerRef || tender.provider_ref), note: text(tender.note) }; }
export function buildPosCheckoutReceipt(cart = {}, tenderInput = []) { const tenders = (Array.isArray(tenderInput) ? tenderInput : []).map(normalizeTenderInput).filter((t) => t.amountCents > 0); const tenderedCents = tenders.reduce((sum, t) => sum + t.amountCents, 0); const totalCents = Number(cart.totalCents ?? cart.total_cents ?? 0); const changeDueCents = Math.max(0, tenderedCents - totalCents); return { paid: tenderedCents >= totalCents && totalCents > 0, totalCents, tenderedCents, changeDueCents, tenders, paymentStatus: tenderedCents >= totalCents ? 'paid' : 'pending_manual' }; }
export function posCartRecord(row) { if (!row) return null; let items = []; let tenders = []; try { items = JSON.parse(row.items_json || row.items || '[]'); } catch {} try { tenders = JSON.parse(row.tenders_json || row.tenders || '[]'); } catch {} return { id: row.id || '', merchantId: row.merchant_id || row.merchantId || '', registerId: row.register_id || row.registerId || '', shiftId: row.shift_id || row.shiftId || '', customerId: row.customer_id || row.customerId || '', status: row.status || 'open', currency: row.currency || 'USD', subtotalCents: Number(row.subtotal_cents ?? row.subtotalCents ?? 0), discountCents: Number(row.discount_cents ?? row.discountCents ?? 0), taxCents: Number(row.tax_cents ?? row.taxCents ?? 0), totalCents: Number(row.total_cents ?? row.totalCents ?? 0), items, tenders, receiptNumber: row.receipt_number || row.receiptNumber || '', orderId: row.order_id || row.orderId || '', createdAt: row.created_at || row.createdAt || '', updatedAt: row.updated_at || row.updatedAt || '' }; }
