const text = (v = '') => String(v || '').trim();
const num = (v, f = 0) => Number.isFinite(Number(v)) ? Math.trunc(Number(v)) : f;
const bool = (v, f = false) => v === undefined || v === null || v === '' ? f : v === true || v === 'true' || v === '1' || v === 1;
const asJson = (v, f) => Array.isArray(v) || (v && typeof v === 'object') ? v : (() => { try { return JSON.parse(v || ''); } catch { return f; } })();
export function normalizeCustomerSegmentInput(body = {}, existing = {}) { const name = text(body.name || existing.name || 'Retail'); return { name, key: text(body.key || existing.key || name).toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'retail', rules: asJson(body.rules, body.rules || existing.rules || {}), active: bool(body.active, existing.active ?? true) }; }
export function customerSegmentRecord(row) { if (!row) return null; let rules = {}; try { rules = JSON.parse(row.rules_json || row.rules || '{}'); } catch {} return { id: row.id || '', merchantId: row.merchant_id || row.merchantId || '', name: row.name || '', key: row.segment_key || row.key || '', rules, active: Boolean(Number(row.active ?? 1)), createdAt: row.created_at || row.createdAt || '', updatedAt: row.updated_at || row.updatedAt || '' }; }
export function normalizePriceListItemInput(item = {}) { const kind = text(item.adjustmentType || item.adjustment_type).toLowerCase(); return { productId: text(item.productId || item.product_id), variantId: text(item.variantId || item.variant_id), adjustmentType: ['fixed', 'percent', 'override'].includes(kind) ? kind : 'percent', adjustmentBps: num(item.adjustmentBps ?? item.adjustment_bps, 0), priceCents: Math.max(0, num(item.priceCents ?? item.price_cents, 0)) }; }
export function normalizePriceListInput(body = {}, existing = {}) { const items = asJson(body.items, body.items || existing.items || []).map(normalizePriceListItemInput).filter((i) => i.productId || i.variantId); return { name: text(body.name || existing.name || 'Wholesale price list'), segmentId: text(body.segmentId || existing.segmentId), currency: text(body.currency || existing.currency || 'USD').toUpperCase(), active: bool(body.active, existing.active ?? true), items }; }
export function priceListItemRecord(row) { if (!row) return null; return { id: row.id || '', priceListId: row.price_list_id || row.priceListId || '', productId: row.product_id || row.productId || '', variantId: row.variant_id || row.variantId || '', adjustmentType: row.adjustment_type || row.adjustmentType || 'percent', adjustmentBps: Number(row.adjustment_bps ?? row.adjustmentBps ?? 0), priceCents: Number(row.price_cents ?? row.priceCents ?? 0), productTitle: row.product_title || row.productTitle || '' }; }
export function priceListRecord(row, items = [], segment = null) { if (!row) return null; return { id: row.id || '', merchantId: row.merchant_id || row.merchantId || '', name: row.name || '', segmentId: row.segment_id || row.segmentId || '', segmentName: row.segment_name || row.segmentName || segment?.name || '', currency: row.currency || 'USD', active: Boolean(Number(row.active ?? 1)), createdAt: row.created_at || row.createdAt || '', updatedAt: row.updated_at || row.updatedAt || '', items: (Array.isArray(items) ? items : []).map(priceListItemRecord).filter(Boolean) }; }
export function resolvePriceListPrice(baseCents = 0, item = {}) { const base = Math.max(0, Number(baseCents || 0)); if (!item) return { priceCents: base, savingsCents: 0, adjustmentType: 'none' }; if (item.adjustmentType === 'override') { const priceCents = Math.max(0, Number(item.priceCents || 0)); return { priceCents, savingsCents: Math.max(0, base - priceCents), adjustmentType: 'override' }; } if (item.adjustmentType === 'fixed') { const priceCents = Math.max(0, base - Math.max(0, Number(item.priceCents || 0))); return { priceCents, savingsCents: Math.max(0, base - priceCents), adjustmentType: 'fixed' }; } const savingsCents = Math.floor(base * Math.max(0, Number(item.adjustmentBps || 0)) / 10000); return { priceCents: Math.max(0, base - savingsCents), savingsCents, adjustmentType: 'percent' }; }
