const text = (v = '') => String(v || '').trim();
const num = (v, f = 0) => Number.isFinite(Number(v)) ? Math.trunc(Number(v)) : f;
const bool = (v, f = false) => v === undefined || v === null || v === '' ? f : v === true || v === 'true' || v === '1' || v === 1;
const asJson = (v, f) => Array.isArray(v) || (v && typeof v === 'object') ? v : (() => { try { return JSON.parse(v || ''); } catch { return f; } })();
export function normalizeSupplierInput(body = {}, existing = {}) { return { name: text(body.name || existing.name || 'Supplier'), contactName: text(body.contactName || existing.contactName), email: text(body.email || existing.email).toLowerCase(), phone: text(body.phone || existing.phone), website: text(body.website || existing.website), countryCode: text(body.countryCode || existing.countryCode || 'US').toUpperCase(), leadTimeDays: Math.max(0, num(body.leadTimeDays ?? existing.leadTimeDays, 0)), minimumOrderCents: Math.max(0, num(body.minimumOrderCents ?? existing.minimumOrderCents, 0)), active: bool(body.active, existing.active ?? true), notes: text(body.notes || existing.notes) }; }
export function supplierRecord(row) { if (!row) return null; return { id: row.id || '', merchantId: row.merchant_id || row.merchantId || '', name: row.name || '', contactName: row.contact_name || row.contactName || '', email: row.email || '', phone: row.phone || '', website: row.website || '', countryCode: row.country_code || row.countryCode || '', leadTimeDays: Number(row.lead_time_days ?? row.leadTimeDays ?? 0), minimumOrderCents: Number(row.minimum_order_cents ?? row.minimumOrderCents ?? 0), active: Boolean(Number(row.active ?? 1)), notes: row.notes || '', createdAt: row.created_at || row.createdAt || '', updatedAt: row.updated_at || row.updatedAt || '' }; }
export function normalizePurchaseOrderItemInput(item = {}) { const quantity = Math.max(1, num(item.quantity, 1)); const unitCostCents = Math.max(0, num(item.unitCostCents ?? item.unit_cost_cents, 0)); return { productId: text(item.productId || item.product_id), variantId: text(item.variantId || item.variant_id), sku: text(item.sku), title: text(item.title), quantity, unitCostCents, receivedQuantity: Math.max(0, num(item.receivedQuantity ?? item.received_quantity, 0)), lineTotalCents: quantity * unitCostCents }; }
export function calculatePurchaseOrderTotals(items = []) { const normalized = (Array.isArray(items) ? items : []).map((i) => ({ quantity: Math.max(0, Number(i.quantity || 0)), unitCostCents: Math.max(0, Number(i.unitCostCents ?? i.unit_cost_cents ?? 0)) })); return { itemCount: normalized.length, unitCount: normalized.reduce((s, i) => s + i.quantity, 0), totalCostCents: normalized.reduce((s, i) => s + i.quantity * i.unitCostCents, 0) }; }
export function normalizePurchaseOrderInput(body = {}, existing = {}) { const items = asJson(body.items, body.items || existing.items || []).map(normalizePurchaseOrderItemInput).filter((i) => i.productId || i.sku || i.title); return { supplierId: text(body.supplierId || existing.supplierId), locationId: text(body.locationId || existing.locationId), status: text(body.status || existing.status || 'draft').toLowerCase() || 'draft', expectedAt: text(body.expectedAt || existing.expectedAt), notes: text(body.notes || existing.notes), currency: text(body.currency || existing.currency || 'USD').toUpperCase(), items, totalCostCents: calculatePurchaseOrderTotals(items).totalCostCents }; }
export function purchaseOrderItemRecord(row) { if (!row) return null; const quantity = Number(row.quantity || 0); const unitCostCents = Number(row.unit_cost_cents ?? row.unitCostCents ?? 0); return { id: row.id || '', purchaseOrderId: row.purchase_order_id || row.purchaseOrderId || '', productId: row.product_id || row.productId || '', variantId: row.variant_id || row.variantId || '', sku: row.sku || '', title: row.title || row.product_title || row.productTitle || '', quantity, receivedQuantity: Number(row.afterReceivedQuantity ?? row.received_quantity ?? row.receivedQuantity ?? 0), unitCostCents, lineTotalCents: Number(row.line_total_cents ?? row.lineTotalCents ?? quantity * unitCostCents) }; }
export function summarizeReceiving(items = []) { const normalized = (Array.isArray(items) ? items : []).map(purchaseOrderItemRecord).filter(Boolean); const orderedUnits = normalized.reduce((s, i) => s + Number(i.quantity || 0), 0); const receivedUnits = normalized.reduce((s, i) => s + Math.min(Number(i.quantity || 0), Number(i.receivedQuantity || 0)), 0); return { orderedUnits, receivedUnits, openUnits: Math.max(0, orderedUnits - receivedUnits), complete: orderedUnits > 0 && receivedUnits >= orderedUnits }; }
export function purchaseOrderRecord(row, items = [], supplier = null) { if (!row) return null; const normalizedItems = (Array.isArray(items) ? items : []).map(purchaseOrderItemRecord).filter(Boolean); return { id: row.id || '', merchantId: row.merchant_id || row.merchantId || '', supplierId: row.supplier_id || row.supplierId || '', supplierName: row.supplier_name || row.supplierName || supplier?.name || '', locationId: row.location_id || row.locationId || '', status: row.status || 'draft', expectedAt: row.expected_at || row.expectedAt || '', receivedAt: row.received_at || row.receivedAt || '', currency: row.currency || 'USD', totalCostCents: Number(row.total_cost_cents ?? row.totalCostCents ?? calculatePurchaseOrderTotals(normalizedItems).totalCostCents), notes: row.notes || '', createdAt: row.created_at || row.createdAt || '', updatedAt: row.updated_at || row.updatedAt || '', items: normalizedItems, receiving: summarizeReceiving(normalizedItems) }; }
export function buildPurchaseOrderReceipt(po = {}, receipt = {}) { const requestedItems = asJson(receipt.items, receipt.items || []); const byItem = new Map(requestedItems.map((i) => [String(i.itemId || i.id || i.productId || i.product_id || ''), Math.max(0, num(i.quantity ?? i.receivedQuantity, 0))])); const items = (po.items || []).map((item) => { const requested = byItem.get(item.id) ?? byItem.get(item.productId) ?? Math.max(0, Number(item.quantity || 0) - Number(item.receivedQuantity || 0)); const remaining = Math.max(0, Number(item.quantity || 0) - Number(item.receivedQuantity || 0)); const receiveQuantity = Math.min(remaining, requested); return { ...item, receiveQuantity, afterReceivedQuantity: Number(item.receivedQuantity || 0) + receiveQuantity }; }); const receivedUnits = items.reduce((sum, i) => sum + i.receiveQuantity, 0); return { receivedUnits, items, complete: items.every((i) => i.afterReceivedQuantity >= Number(i.quantity || 0)), note: text(receipt.note) }; }
