import { asArray, cleanText, nowIso, receiptId, slugify } from "../utils.mjs";

function htmlEscape(value) {
  return cleanText(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function routeToFile(route) {
  const clean = cleanText(route || "/");
  if (clean === "/" || clean === "index") return "index.html";
  return `${clean.replace(/^\/+/, "").replace(/\/+$/, "")}/index.html`;
}

function sectionForTask(task) {
  const contract = task.contract || {};
  if (contract.operation === "upsert_faq_block") {
    return `<section class="agentic-faq" data-agentic-source="${htmlEscape(task.id)}">
  <h2>${htmlEscape(contract.question || "Frequently asked question")}</h2>
  <p>${htmlEscape(contract.answerBrief || "Draft answer pending operator review.")}</p>
</section>`;
  }
  if (contract.operation === "add_internal_links") {
    const links = asArray(contract.sourceRoutes).map((route) => `<li><a href="${htmlEscape(contract.route)}">${htmlEscape(contract.anchorText || route)}</a></li>`).join("\n    ");
    return `<nav class="agentic-related-links" data-agentic-source="${htmlEscape(task.id)}" aria-label="Related pages">
  <h2>Related pages</h2>
  <ul>
    ${links}
  </ul>
</nav>`;
  }
  if (contract.operation === "create_or_refresh_proof_page") {
    return `<section class="agentic-proof" data-agentic-source="${htmlEscape(task.id)}">
  <h1>Proof for ${htmlEscape(task.targetRoute || "this service")}</h1>
  <p>${htmlEscape(contract.pageBrief || "Attach verified proof before publishing.")}</p>
  <a href="/contact" class="agentic-cta">Request the proof packet</a>
</section>`;
  }
  return `<section class="agentic-growth-section" data-agentic-source="${htmlEscape(task.id)}">
  <h1>${htmlEscape(task.title || "Growth page update")}</h1>
  <p>${htmlEscape(contract.pageBrief || "Draft improvement generated by the agentic growth layer.")}</p>
  <a href="/contact" class="agentic-cta">Request a quote</a>
</section>`;
}

function operationForTask(task) {
  const contract = task.contract || {};
  const route = contract.route || task.targetRoute || "/";
  const file = routeToFile(route);
  const mode = contract.operation?.startsWith("create") || task.title?.toLowerCase().includes("build")
    ? "upsert_file"
    : "upsert_section";
  return {
    op: mode,
    route,
    file,
    selector: "main",
    html: sectionForTask(task),
    acceptance: asArray(contract.acceptance),
    approval: contract.approval || "human_review_recommended",
    sourceTaskId: task.id
  };
}

export function buildStaticSitePatch(plan = {}, options = {}) {
  const tasks = asArray(plan.developerTasks);
  const operations = tasks.map(operationForTask);
  const receipt = {
    id: receiptId("agl_static_patch"),
    createdAt: nowIso(),
    adapter: "static-site",
    mode: options.mode || "proposal_only",
    sourcePlanId: plan.receipt?.id || "",
    operationCount: operations.length
  };

  const files = [
    {
      path: "agentic-growth/AGENTIC_GROWTH_RECEIPT.json",
      contentType: "application/json",
      body: JSON.stringify({ receipt, planReceipt: plan.receipt, operations }, null, 2)
    },
    {
      path: "agentic-growth/agentic-growth.css",
      contentType: "text/css",
      body: `.agentic-cta{display:inline-flex;align-items:center;min-height:44px;padding:10px 14px;border-radius:6px;background:#111827;color:#fff;text-decoration:none}.agentic-related-links ul{display:grid;gap:8px;padding-left:18px}.agentic-proof,.agentic-faq,.agentic-growth-section{padding:48px 0}`
    }
  ];

  for (const operation of operations.filter((item) => item.op === "upsert_file")) {
    files.push({
      path: operation.file,
      contentType: "text/html",
      body: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${htmlEscape(operation.route.replace(/^\/+/, "").replace(/-/g, " ") || "Growth page")}</title>
  <link rel="stylesheet" href="/agentic-growth/agentic-growth.css">
</head>
<body>
  <main>
${operation.html}
  </main>
</body>
</html>`
    });
  }

  return {
    ok: true,
    receipt,
    operations,
    files,
    install: {
      serverToServerOnly: true,
      exampleEndpoint: "/api/agentic-growth/v1/cycles",
      netlifyFunctionRoute: "/.netlify/functions/agentic-growth-cycle",
      note: "Do not expose provider API keys in browser code. Call the growth API from a server function, Worker, build job, or CMS plugin."
    },
    suggestedBranchName: `agentic-growth/${slugify(plan.receipt?.label || "growth-cycle")}`
  };
}
